// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace Shared_Static_Class.Data;

[Table("DEMANDA_CHAMADO", Schema = "Demandas")]
public partial class DEMANDA_CHAMADO
{
    [Key]
    public int ID { get; set; }
    [Required]
    public Guid ID_RELACAO { get; set; }
    public int ID_FILA_CHAMADO { get; set; }

    [Unicode(false)]
    public int? MATRICULA_RESPONSAVEL { get; set; }

    [Unicode(false)]
    public int MATRICULA_SOLICITANTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_ABERTURA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_FECHAMENTO { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string PRIORIDADE { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string REGIONAL { get; set; }
    public int? CLIENTE_ALTO_VALOR { get; set; } = null;

    /* --------------------------------------- Propriedades com ligação em tabela de relação --------------------------------------- */
    //[InverseProperty("DEMANDANav")]
    //[JsonIgnore]
    //public virtual ICollection<DEMANDA_CHAMADO_RESPOSTA> Respostas { get; set; } = new List<DEMANDA_CHAMADO_RESPOSTA>();
    //[InverseProperty("DEMANDANav")]
    //[JsonIgnore]
    //public virtual ICollection<DEMANDA_STATUS_CHAMADO> Status { get; set; } = new List<DEMANDA_STATUS_CHAMADO>();
    /* -------------------------------------- Propriedades com ligação em tabela de relação --------------------------------------- */

    /* --------------------------------------- Propriedades com ligação direta com a tabela --------------------------------------- */
    [InverseProperty("DEMANDANav")]
    [JsonIgnore]
    public virtual ICollection<DEMANDA_CAMPOS_CHAMADO> Campos { get; set; } = new List<DEMANDA_CAMPOS_CHAMADO>();
    [InverseProperty("DEMANDANav")]
    [JsonIgnore]
    
    public virtual ICollection<DEMANDA_HISTORICO_PRIORIDADE> Historico_Prioridade { get; set; } = new List<DEMANDA_HISTORICO_PRIORIDADE>();
    
    [InverseProperty("DEMANDANav")]
    [JsonIgnore]
    public virtual DEMANDA_AVALIACAO_ANALISTA? Avaliacao_Solicitante { get; set; }
    /* --------------------------------------- Propriedades com ligação direta com a tabela --------------------------------------- */

    [ForeignKey("ID_RELACAO")]
    public virtual DEMANDA_RELACAO_CHAMADO Relacao { get; set; }

    [ForeignKey("CLIENTE_ALTO_VALOR")]
    [JsonIgnore]
    public virtual DEMANDA_PARQUE? Has_Cliente_Valor { get; set; }

    [ForeignKey("MATRICULA_RESPONSAVEL")]
    [JsonIgnore]
    public virtual ACESSOS_MOBILE? Responsavel { get; set; }

    [ForeignKey("MATRICULA_SOLICITANTE")]
    [JsonIgnore]
    public virtual ACESSOS_MOBILE Solicitante { get; set; }

    [ForeignKey("ID_FILA_CHAMADO")]
    [InverseProperty("DEMANDAS")]
    [JsonIgnore]
    public virtual DEMANDA_SUB_FILA Fila { get; set; }

}

