// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace Shared_Static_Class.Data;

[Table("DEMANDA_CHAMADO_RESPOSTA", Schema = "Demandas")]
public partial class DEMANDA_CHAMADO_RESPOSTA
{
    [Key]
    public int ID { get; set; }

    [Required]
    [Unicode(false)]
    public string RESPOSTA { get; set; }

    public int ID_CHAMADO { get; set; }
    public Guid ID_RELACAO_CHAMADO { get; set; }

    [Unicode(false)]
    public int MATRICULA_RESPONSAVEL { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA_RESPOSTA { get; set; }

    [ForeignKey("ID_RELACAO_CHAMADO")]
    public virtual DEMANDA_RELACAO_CHAMADO Relacao_DEMANDA { get; set; }

    [InverseProperty("RESPOSTANav")]
    [JsonIgnore]
    public virtual ICollection<DEMANDA_ARQUIVOS_RESPOSTA>? ARQUIVOS { get; set; } = new List<DEMANDA_ARQUIVOS_RESPOSTA>();

    [InverseProperty("Resposta")]
    public virtual DEMANDA_STATUS_CHAMADO? Status { get; set; } // Status 

    [ForeignKey("MATRICULA_RESPONSAVEL")]
    public virtual ACESSOS_MOBILE Responsavel { get; set; }
}