// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Newtonsoft.Json;

namespace Shared_Static_Class.Data;

[Table("DEMANDA_RELACAO_CHAMADO", Schema = "Demandas")]
public partial class DEMANDA_RELACAO_CHAMADO
{
    [Key]
    public Guid ID { get; set; }
    public int ID_CHAMADO { get; set; }
    public int Sequence { get; set; }
    [Required]
    public Tabela_Demanda Tabela { get; set; }

    /** Tabelas de relação **/
    [InverseProperty("Relacao")]
    public virtual DEMANDA_CHAMADO? ChamadoRelacao { get; set; } = null;
    [InverseProperty("Relacao")]
    public virtual DEMANDA_ACESSOS? AcessoRelacao { get; set; } = null;
    [InverseProperty("Relacao")]
    public virtual DEMANDA_DESLIGAMENTOS? DesligamentoRelacao { get; set; } = null;

    [InverseProperty("Relacao_DEMANDA")]
    [JsonIgnore]
    public virtual ICollection<DEMANDA_CHAMADO_RESPOSTA> Respostas { get; set; } = new List<DEMANDA_CHAMADO_RESPOSTA>();
    [InverseProperty("Relacao_DEMANDA")]
    [JsonIgnore]
    public virtual ICollection<DEMANDA_STATUS_CHAMADO> Status { get; set; } = new List<DEMANDA_STATUS_CHAMADO>();
    /** Tabelas de relação **/

    public enum Tabela_Demanda
    {
        ChamadoRelacao = 1,
        AcessoRelacao = 2,
        DesligamentoRelacao = 3
    }
}
