// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Newtonsoft.Json;
using Shared_Static_Class.Model_Demanda_Context;
using Shared_Static_Class.Model_DTO;

namespace Shared_Static_Class.Data;

[Table("PRODUTOS_CARDAPIO_AVALIACAO", Schema = "Cardapio")]
[Owned]
public partial class PRODUTO_AVALIACAO
{
    public PRODUTO_AVALIACAO()
    {
    }

    public PRODUTO_AVALIACAO(int avaliacao, int positionInRank, Guid? id_avaliacao = null, Guid? id_produto = null)
    {
        ID_AVALIACAO = id_avaliacao ?? Guid.Empty;
        ID_PRODUTO = id_produto ?? Guid.Empty;
        Avaliacao = avaliacao;
        PositionInRank = positionInRank;
    }

    [Key]
    public Guid ID_AVALIACAO { get; set; }
    public Guid ID_PRODUTO { get; set; }
    [Range(0, 100)]
    public int Avaliacao { get; set; }
    /// <summary>
    /// Posição no ranking, esta propriedade pode ser alterada rapidamente
    /// </summary>
    public int PositionInRank { get; set; }
    public bool IsTop10()
    {
        return PositionInRank <= 10;
    }
    public bool IsTop5()
    {
        return PositionInRank <= 5;
    }
    public bool IsTop3()
    {
        return PositionInRank <= 3;
    }
    public PRODUTOS_CARDAPIO Produto { get; set; }

}
