// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Newtonsoft.Json;
using Shared_Static_Class.Model_Demanda_Context;
using Shared_Static_Class.Model_DTO;

namespace Shared_Static_Class.Data;

[Table("PRODUTOS_CARDAPIO", Schema = "Cardapio")]
public partial class PRODUTOS_CARDAPIO
{
    [Key]
    public Guid ID_PRODUTO { get; set; }
    [MaxLength(255)]
    public string Nome { get; set; }
    [MaxLength(1200)]
    public string Descrição { get; set; }
    [Range(0, 100)]
    public int Avaliacao { get; set; }
    public Categoria Categoria { get; set; }
    public string Fabricante { get; set; }
    public string Cor { get; set; }
    public bool IsOferta { get; set; } = false;
    public decimal Valor { get; set; } = 0;
    public int MaxParcelas { get; set; } = 0;
    public int MaxParcelasSemJuros { get; set; } = 0;
    public DateTime DATA_INCLUSÃO { get; set; }
    public DateTime DATA_MODIFICAÇÃO { get; set; }
    public int MAT_INCLUSÃO { get; set; }
    public int MAT_MODIFICAÇÃO { get; set; }
    public ACESSOS_MOBILE Responsavel_Inclusao { get; set; }
    public ACESSOS_MOBILE Responsavel_Modificacao { get; set; }
    public List<FICHA_TECNICA> Ficha { get; set; } = [];
    public List<PRODUTO_IMAGEM> Imagens { get; set; } = [];
}

public enum Categoria
{
    SMARTPHONE,
    NOTEBOOK,
    CONSOLE,
    CASA_INTELIGENTE,
    GAMES,
    CUIDADO_PESSOAL,
    MODA,
    ACESSÓRIOS,
    AÚDIO_VÍDEO
}
