// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("ACAO_DOCUMENTACAO")]
public partial class ACAO_DOCUMENTACAO
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string DATACADASTRO { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string PROTOCOLO { get; set; }

    [Required]
    public byte[] DOCUMENTOS { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string NOME_ARQUIVO { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string EXTENSAO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DT_APROVACAO_SUPORTE { get; set; }

    [Unicode(false)]
    public string OBS_APROVACAO_SUPORTE { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string STATUS_SUPORTE { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DT_APROVACAO_QUALIDADE { get; set; }

    [Unicode(false)]
    public string OBS_APROVACAO_QUALIDADE { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string STATUS_QUALIDADE { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DT_APROVACAO_MKT { get; set; }

    [Unicode(false)]
    public string OBS_APROVACAO_MKT { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string STATUS_MKT { get; set; }
}