// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("ACAO_ACOMPANHAMENTO")]
public partial class ACAO_ACOMPANHAMENTO
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    public string PROTOCOLO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string NUMERO_PROTOCOLO { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string DOC_SAP { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_SOLICITACAO_PROTOCOLO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_VENCIMENTO_PROTOCOLO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string REL { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_SOLICITACAO_REL { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_VENCIMENTO_REL { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_UPLOAD_PROCESSO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ENVIADO_PARA_SUPORTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RECEBIDO_SUPORTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ENVIADO_PARA_MKT { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ENVIADO_QUALIDADE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ENVIADO_CANAL { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ENVIADO_MKT { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ENVIADO_SUPORTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ENVIADO_JU { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string STATUS_PAGAMENTO { get; set; }

    [Unicode(false)]
    public string OBS { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA_STATUS { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RECEBIDO_QUALIDADE { get; set; }

    public byte[] ARQUIVO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string STATUS_AUDITORIA { get; set; }
}