// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("ACAO_CADASTRO")]
public partial class ACAO_CADASTRO
{
    [Key]
    public int id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string adabas { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string regional { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string praca { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string ddd { get; set; }

    public int idTipo { get; set; }

    public int idDetalhada { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string veiculo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string descricaoAcao { get; set; }

    public int? dia1 { get; set; }

    public int? dia2 { get; set; }

    public int? dia3 { get; set; }

    public int? dia4 { get; set; }

    public int? dia5 { get; set; }

    public int? dia6 { get; set; }

    public int? dia7 { get; set; }

    public int? dia8 { get; set; }

    public int? dia9 { get; set; }

    public int? dia10 { get; set; }

    public int? dia11 { get; set; }

    public int? dia12 { get; set; }

    public int? dia13 { get; set; }

    public int? dia14 { get; set; }

    public int? dia15 { get; set; }

    public int? dia16 { get; set; }

    public int? dia17 { get; set; }

    public int? dia18 { get; set; }

    public int? dia19 { get; set; }

    public int? dia20 { get; set; }

    public int? dia21 { get; set; }

    public int? dia22 { get; set; }

    public int? dia23 { get; set; }

    public int? dia24 { get; set; }

    public int? dia25 { get; set; }

    public int? dia26 { get; set; }

    public int? dia27 { get; set; }

    public int? dia28 { get; set; }

    public int? dia29 { get; set; }

    public int? dia30 { get; set; }

    public int? dia31 { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string campanhaMacro { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string mesAcao { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string midiaExclusivaVivo { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal valorTotalAcao { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal valorTotalVivo { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string percentParticipacaoVivo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string justificativa { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string focoPrincipal { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string qtdAcoes { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string insercoes { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string origemVerba { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string observacoes { get; set; }

    public int idStatus { get; set; }

    public int idAcesso { get; set; }

    public int idAcessoCadastro { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string formatoMaterial { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal CustoUnitario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? dataFinalizacao { get; set; }

    [Required]
    [StringLength(255)]
    public string Protocolo { get; set; }

    [StringLength(50)]
    public string IXO { get; set; }

    [StringLength(255)]
    public string NomeContatoRede { get; set; }

    [StringLength(50)]
    public string TelefoneContatoRede { get; set; }

    [StringLength(255)]
    public string EmailContatoRede { get; set; }

    [StringLength(255)]
    public string Consideracao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataPreenchimentoInicial { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataPreenchimentoFinal { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string PercentualRede { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? ValorTotalRede { get; set; }

    [Unicode(false)]
    public string DevolucaoMarketing { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataValidacao { get; set; }

    public string Cidade { get; set; }

    [InverseProperty("IDVPCNavigation")]
    public virtual ICollection<ACAO_HISTORICO> ACAO_HISTORICOs { get; set; } = new List<ACAO_HISTORICO>();
}