// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("ACAO_SALDO_REDE")]
public partial class ACAO_SALDO_REDE
{
    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Rede { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? Saldo_VPC { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? Saldo_VIO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Regional { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataInput { get; set; }
}