// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("ACESSO_TERCEIROS_SISTEMAS")]
public partial class ACESSO_TERCEIROS_SISTEMA
{
    [Key]
    public int Id { get; set; }

    public int? Id_Acesso { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Sistema { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Login { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Senha { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AceiteSenha { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RejeitarSenha { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataSenha { get; set; }
}