// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("ACESSO_TERCEIROS_OBSERVACAO")]
public partial class ACESSO_TERCEIROS_OBSERVACAO
{
    [Key]
    public int ID { get; set; }

    public int? ID_ACESSO_TERCEIRO { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string OBSERVACAO { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string DATA_INICIO { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string DATA_FIM { get; set; }
}