// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("ACESSO_CARGO_PERFIL")]
public partial class ACESSO_CARGO_PERFIL
{
    [StringLength(255)]
    public string GERÊNCIA { get; set; }

    [StringLength(255)]
    public string CARGO { get; set; }

    [StringLength(255)]
    public string DescricaoMenu { get; set; }

    [StringLength(255)]
    public string TipoAcesso { get; set; }
}