// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("ADMISSAO")]
public partial class ADMISSAO
{
    public int id { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string Uf { get; set; }

    [Required]
    [StringLength(8)]
    [Unicode(false)]
    public string Matricula { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Candidato { get; set; }

    [Required]
    [StringLength(14)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Cargo { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Gestor { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Loja { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string DataAdmissao { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string NomeMae { get; set; }

    public int? IdAcesso { get; set; }
}