// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("ALTA_SEM_TRAFEGO_STATUS")]
public partial class ALTA_SEM_TRAFEGO_STATUS
{
    [Key]
    public int Id { get; set; }

    public int IdAST { get; set; }

    [StringLength(300)]
    [Unicode(false)]
    public string OBSERVACAO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RETORNO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA_ULTIMA_ALTERACAO { get; set; }

    public int ID_SOLICITANTE_ALTERACAO { get; set; }

    [ForeignKey("IdAST")]
    [InverseProperty("ALTA_SEM_TRAFEGO_STATUSes")]
    public virtual ALTA_SEM_TRAFEGO IdASTNavigation { get; set; }
}