// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("ALTA_SEM_TRAFEGO")]
public partial class ALTA_SEM_TRAFEGO
{
    [StringLength(255)]
    public string ANOMES { get; set; }

    [StringLength(255)]
    public string NU_ANO_MES_RFRN { get; set; }

    [StringLength(255)]
    public string DIVISAO { get; set; }

    [StringLength(255)]
    public string DS_SGMT_PRDT { get; set; }

    [StringLength(255)]
    public string DS_PRDT { get; set; }

    [StringLength(255)]
    public string DS_CTGR_PRDT { get; set; }

    [StringLength(255)]
    public string NO_PLNO { get; set; }

    [StringLength(255)]
    public string CD_CRDN { get; set; }

    [StringLength(255)]
    public string NO_REDE { get; set; }

    [StringLength(255)]
    public string CANAL { get; set; }

    [StringLength(255)]
    public string LOGIN { get; set; }

    [StringLength(255)]
    public string NM_VEND { get; set; }

    [StringLength(255)]
    public string GERENTE_CONTAS { get; set; }

    [StringLength(255)]
    public string GERENTE_TERRITORIAL { get; set; }

    [StringLength(255)]
    public string NOMEFANTASIA { get; set; }

    [StringLength(255)]
    public string STATUS_PDV { get; set; }

    [StringLength(255)]
    public string QT_TOTL_FSCO { get; set; }

    [StringLength(255)]
    public string QT_LNHA_TRFG { get; set; }

    [StringLength(255)]
    public string QT_PRQE_ANTR { get; set; }

    [StringLength(255)]
    public string FL_SEM_TRFG { get; set; }

    [Key]
    public int ID { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string NU_TLFN { get; set; }

    [InverseProperty("IdASTNavigation")]
    public virtual ICollection<ALTA_SEM_TRAFEGO_STATUS> ALTA_SEM_TRAFEGO_STATUSes { get; set; } = new List<ALTA_SEM_TRAFEGO_STATUS>();
}