// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("APROVADORES$")]
public partial class APROVADORES_
{
    [StringLength(255)]
    public string CNPJ { get; set; }

    [Column("Seção Territorial")]
    [StringLength(255)]
    public string Seção_Territorial { get; set; }

    [Column("Unidade Gestor Operacional")]
    public double? Unidade_Gestor_Operacional { get; set; }

    [Column("Unidade Gestor Contrato")]
    public double? Unidade_Gestor_Contrato { get; set; }
}