// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("ARQUIVOS_PRESTACAO_COMPROVANTE")]
public partial class ARQUIVOS_PRESTACAO_COMPROVANTE
{
    public int ID { get; set; }

    public int ID_PRESTACAO { get; set; }

    [Unicode(false)]
    public string DIA { get; set; }

    [Unicode(false)]
    public string TIPO { get; set; }

    public double? VALOR { get; set; }

    public byte[] ARQUIVO { get; set; }

    [Unicode(false)]
    public string NOME_ARQUIVO { get; set; }
}