// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("BAIRROS")]
public partial class BAIRRO
{
    public int bairro_id { get; set; }

    public int cidade_id { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string desc_bairro { get; set; }
}