// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BASE_SIGITIM")]
public partial class BASE_SIGITIM
{
    [Key]
    public int ID { get; set; }

    [Unicode(false)]
    public string SEQUENCIA { get; set; }

    [Unicode(false)]
    public string ORIGEM { get; set; }

    [Unicode(false)]
    public string DATA_CRIACAO { get; set; }

    [Unicode(false)]
    public string ALARME { get; set; }

    [Unicode(false)]
    public string SIGLA_ESTADO { get; set; }

    [Unicode(false)]
    public string DATA_DE_BAIXA { get; set; }

    [Unicode(false)]
    public string HOST { get; set; }

    [Unicode(false)]
    public string IMPACTO_EQP { get; set; }

    [Unicode(false)]
    public string ENDERECO { get; set; }

    [Unicode(false)]
    public string NOME_MUNICIPIO { get; set; }

    [Unicode(false)]
    public string BAIRRO { get; set; }

    [Unicode(false)]
    public string TIPO_DE_PLANTA { get; set; }

    [Unicode(false)]
    public string VTAPK { get; set; }
}