// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BASE_VAT_ARQUIVOS")]
public partial class BASE_VAT_ARQUIVO
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ID_VAT { get; set; }

    public byte[] ARQUIVO { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string NOME_ARQUIVO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EXTENSAO_ARQUIVO { get; set; }
}