// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("BASE_PROJETO_LORENA")]
public partial class BASE_PROJETO_LORENA
{
    public double? RE { get; set; }

    [Unicode(false)]
    public string CPF { get; set; }

    [Unicode(false)]
    public string Nome { get; set; }

    [Unicode(false)]
    public string FUNÇÃO { get; set; }

    [Unicode(false)]
    public string Regional { get; set; }

    [Unicode(false)]
    public string UF { get; set; }

    [Unicode(false)]
    public string Rede { get; set; }

    [Column("PDV - Adabas")]
    [Unicode(false)]
    public string PDV___Adabas { get; set; }

    [Column("PDV - Login Siebel")]
    [Unicode(false)]
    public string PDV___Login_Siebel { get; set; }

    [Unicode(false)]
    public string Status { get; set; }
}