// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("BASE_NOMECLATURA_SAP_LLPP")]
public partial class BASE_NOMECLATURA_SAP_LLPP
{
    [StringLength(255)]
    public string CENTRO { get; set; }

    [StringLength(255)]
    public string ESCV { get; set; }

    [StringLength(255)]
    public string CNPJ { get; set; }

    [StringLength(255)]
    public string NOME_SAP { get; set; }

    [StringLength(255)]
    public string NOME_CARTEIRA { get; set; }

    [StringLength(255)]
    public string EMAIL { get; set; }
}