// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BASE_SIGITIM_SUL")]
public partial class BASE_SIGITIM_SUL
{
    [Key]
    public int ID { get; set; }

    [Unicode(false)]
    public string DDD { get; set; }

    [Unicode(false)]
    public string NOME_ESTADO { get; set; }

    [Unicode(false)]
    public string NOME_MUNICIPIO { get; set; }

    [Unicode(false)]
    public string Bairro { get; set; }

    [Unicode(false)]
    public string Sequencia { get; set; }

    [Unicode(false)]
    public string Origem { get; set; }

    [Unicode(false)]
    public string Raiz { get; set; }

    [Unicode(false)]
    public string Tecnologia { get; set; }

    [Column("Data Criacao")]
    [Unicode(false)]
    public string Data_Criacao { get; set; }

    [Column("Data Encerramento")]
    [Unicode(false)]
    public string Data_Encerramento { get; set; }

    [Column("Tipo Planta")]
    [Unicode(false)]
    public string Tipo_Planta { get; set; }

    [Column("Tipo Afetacao")]
    [Unicode(false)]
    public string Tipo_Afetacao { get; set; }

    [Unicode(false)]
    public string VTAPK { get; set; }
}