// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BOLETA_TIPO_VENDA")]
public partial class BOLETA_TIPO_VENDum
{
    [Key]
    public int ID { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string TIPO_VENDA { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string MOTIVO_NAO_VENDA { get; set; }
}