// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BOLETA_ITEM_VENDA_MIGRACAO")]
public partial class BOLETA_ITEM_VENDA_MIGRACAO
{
    [Key]
    public int Id { get; set; }

    public int IdVenda { get; set; }

    [Unicode(false)]
    public string Produto { get; set; }

    [Unicode(false)]
    public string Plano { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? Valor { get; set; }

    [Unicode(false)]
    public string DataVencimento { get; set; }

    [Unicode(false)]
    public string IMEI { get; set; }

    [Unicode(false)]
    public string ICCID { get; set; }

    [Unicode(false)]
    public string CodFatIMEI { get; set; }

    [Unicode(false)]
    public string CodFatICCID { get; set; }

    [Unicode(false)]
    public string CodMaterial { get; set; }

    [Unicode(false)]
    public string ProtocoloGed { get; set; }

    [StringLength(13)]
    [Unicode(false)]
    public string LinhaProvisoria { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string STATUS { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    [InverseProperty("IDITEMVENDANavigation")]
    public virtual ICollection<BOLETA_CHECKLIST_QUALIDADE_VENDA_MIGRACAO> BOLETA_CHECKLIST_QUALIDADE_VENDA_MIGRACAOs { get; set; } = new List<BOLETA_CHECKLIST_QUALIDADE_VENDA_MIGRACAO>();

    [ForeignKey("IdVenda")]
    [InverseProperty("BOLETA_ITEM_VENDA_MIGRACAOs")]
    public virtual BOLETA_VENDum IdVendaNavigation { get; set; }
}