// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BOLETA_BD_CLIENTES")]
public partial class BOLETA_BD_CLIENTE
{
    [Key]
    public int ID_CLIENTE_BOLETA { get; set; }

    public int ID_BOLETA { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string NOME { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CPF_CNPJ { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string TELEFONE { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string SENHA_GSS { get; set; }

    [ForeignKey("ID_BOLETA")]
    [InverseProperty("BOLETA_BD_CLIENTEs")]
    public virtual BOLETA_BD_PALITAGEM ID_BOLETANavigation { get; set; }
}