// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BOLETA_ALTA")]
public partial class BOLETA_ALTum
{
    [Key]
    public int Id { get; set; }

    public int? Id_Dados { get; set; }

    [Unicode(false)]
    public string Produto { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Linha { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string LinhaPortabilidade { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ComFidelizacao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Portabilidade { get; set; }

    [Unicode(false)]
    public string Device { get; set; }

    [Unicode(false)]
    public string Plano { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? Valor { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? ValorDevice { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MatriculaCN { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Data_Vencimento { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string PLANO2 { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string LINHA2 { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? VALOR2 { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string PLANO3 { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string LINHA3 { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? VALOR3 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string D0 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ComMigracaoTecnologia { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Convergencia { get; set; }
}