// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BOLETA_BD_BLOCAO")]
public partial class BOLETA_BD_BLOCAO
{
    [Key]
    public int ID_BLOCAO_BOLETA { get; set; }

    public int ID_BOLETA { get; set; }

    [InverseProperty("ID_BLOCAO_BOLETANavigation")]
    public virtual ICollection<BOLETA_BD_DADO> BOLETA_BD_DADOs { get; set; } = new List<BOLETA_BD_DADO>();

    [ForeignKey("ID_BOLETA")]
    [InverseProperty("BOLETA_BD_BLOCAOs")]
    public virtual BOLETA_BD_PALITAGEM ID_BOLETANavigation { get; set; }
}