// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("BOLETA_STATUS")]
public partial class BOLETA_STATUS
{
    public int? Id { get; set; }

    public int? Id_Boleta { get; set; }

    [StringLength(350)]
    [Unicode(false)]
    public string Device { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string IMEI { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string ICCID { get; set; }

    [StringLength(350)]
    [Unicode(false)]
    public string TIPO_SOLICITACAO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LOGIN { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FINALIZADO { get; set; }

    public int? IdPedido { get; set; }
}