// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("BOLETA_CURVA_META_DIA")]
public partial class BOLETA_CURVA_META_DIum
{
    [Unicode(false)]
    public string PDV { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia1 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia3 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia4 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia5 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia6 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia7 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia8 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia9 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia10 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia11 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia12 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia13 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia14 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia15 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia16 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia17 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia18 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia19 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia20 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia21 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia22 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia23 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia24 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia25 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia26 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia27 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia28 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia29 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia30 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ValorTotal { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dia31 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_CARGA { get; set; }
}