// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BOLETA_BD_DADOS")]
public partial class BOLETA_BD_DADO
{
    [Key]
    public int ID_DADOS_BOLETA { get; set; }

    public int ID_BLOCAO_BOLETA { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string PLATAFORMA { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string MOVIMENTO { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CATEGORIA { get; set; }

    public bool? PORTABILIDADE { get; set; }

    public bool? FIDELIZACAO { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string PLANO { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string DESCRICAO { get; set; }

    public bool? SVA { get; set; }

    public int ID_BOLETA { get; set; }

    [InverseProperty("ID_DADOS_BOLETANavigation")]
    public virtual ICollection<BOLETA_BD_EQUIPAMENTO> BOLETA_BD_EQUIPAMENTOs { get; set; } = new List<BOLETA_BD_EQUIPAMENTO>();

    [InverseProperty("ID_DADOS_BOLETANavigation")]
    public virtual ICollection<BOLETA_BD_LINHA> BOLETA_BD_LINHAs { get; set; } = new List<BOLETA_BD_LINHA>();

    [InverseProperty("ID_DADOS_BOLETANavigation")]
    public virtual ICollection<BOLETA_BD_SVA> BOLETA_BD_SVAs { get; set; } = new List<BOLETA_BD_SVA>();

    [ForeignKey("ID_BLOCAO_BOLETA")]
    [InverseProperty("BOLETA_BD_DADOs")]
    public virtual BOLETA_BD_BLOCAO ID_BLOCAO_BOLETANavigation { get; set; }
}