// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BOLETA_DADOS_VENDA")]
public partial class BOLETA_DADOS_VENDum
{
    [Key]
    public int Id { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string NomeCliente { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CpfCliente { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string EmailCliente { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MatriculaCN { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Tipo_Venda { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Finalizado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataFinalizacao { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Sistema { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string Loja { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SenhaGSS { get; set; }
}