// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("BOLETA_ITEM_VENDA_SEGUNDA_VIA_FATURA")]
public partial class BOLETA_ITEM_VENDA_SEGUNDA_VIA_FATURA
{
    public int Id { get; set; }

    public int IdVenda { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }
}