// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BOLETA_BD_EQUIPAMENTOS")]
public partial class BOLETA_BD_EQUIPAMENTO
{
    [Key]
    public int ID_EQUIPAMENTO_BOLETA { get; set; }

    public int ID_DADOS_BOLETA { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string MODELO { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string IMEI { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string MATERIAL { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string FATURAMENTO { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string NOTA_FISCAL { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? VALOR { get; set; }

    [ForeignKey("ID_DADOS_BOLETA")]
    [InverseProperty("BOLETA_BD_EQUIPAMENTOs")]
    public virtual BOLETA_BD_DADO ID_DADOS_BOLETANavigation { get; set; }
}