// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BOLETA_NAO_VENDA")]
public partial class BOLETA_NAO_VENDum
{
    [Key]
    public int ID { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string NOME_CLIENTE { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string TELEFONE_CLIENTE { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string TIPO_VENDA { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string MOTIVO_NAO_VENDA { get; set; }

    [Unicode(false)]
    public string MOTIVO_DESCRICAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string IDACESSO { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string CLIENTE_BASE { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string RECEITA { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string QUANTIDADE { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string OPERADORA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FINALIZADO { get; set; }
}