// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("BOOK_PLANOS_8X")]
public partial class BOOK_PLANOS_8X
{
    [StringLength(255)]
    public string PLANO { get; set; }

    [Column("NOMENCLATURA SISTÊMICA VIVO 360")]
    [StringLength(255)]
    public string NOMENCLATURA_SISTÊMICA_VIVO_360 { get; set; }

    [Column("PREÇO ASSINATURA", TypeName = "money")]
    public decimal? PREÇO_ASSINATURA { get; set; }

    [Column("PREÇO FRANQUIA", TypeName = "money")]
    public decimal? PREÇO_FRANQUIA { get; set; }

    [Column("VALOR TOTAL", TypeName = "money")]
    public decimal? VALOR_TOTAL { get; set; }

    [Column("NOME PLANO SAP TABELA MAIS VIVO")]
    [StringLength(255)]
    public string NOME_PLANO_SAP_TABELA_MAIS_VIVO { get; set; }

    [Column("NOME PLANO SAP TABELA RENOVA")]
    [StringLength(255)]
    public string NOME_PLANO_SAP_TABELA_RENOVA { get; set; }

    [Column("FRANQUIA OUTRAS OPERADORAS  - LIGAÇÃO LOCAL")]
    [StringLength(255)]
    public string FRANQUIA_OUTRAS_OPERADORAS____LIGAÇÃO_LOCAL { get; set; }

    [Column("FRANQUIA DE DADOS")]
    [StringLength(255)]
    public string FRANQUIA_DE_DADOS { get; set; }

    [Column("N° DE MULTIVIVOS")]
    public double? N__DE_MULTIVIVOS { get; set; }

    [Column("MULTIVIVOS COMPATÍVEIS")]
    [StringLength(255)]
    public string MULTIVIVOS_COMPATÍVEIS { get; set; }

    [Column("CÓD# HOMOLOGAÇÃO")]
    public double? CÓD__HOMOLOGAÇÃO { get; set; }

    [Column("MATRIZ OFERTA")]
    public string MATRIZ_OFERTA { get; set; }

    [Column("FIDELIZAÇÃO/ CONTRATO")]
    [StringLength(255)]
    public string FIDELIZAÇÃO__CONTRATO { get; set; }

    [Column("VALOR DA MULTA", TypeName = "money")]
    public decimal? VALOR_DA_MULTA { get; set; }

    [Column("PACOTE ADICIONAL INTERNET")]
    public string PACOTE_ADICIONAL_INTERNET { get; set; }

    [Column("BLOQUEIO DE DADOS")]
    [StringLength(255)]
    public string BLOQUEIO_DE_DADOS { get; set; }

    [Column("PROMOÇÕES VIGENTES")]
    public string PROMOÇÕES_VIGENTES { get; set; }

    [Column("VALIDADE DAS PROMOÇÕES")]
    public string VALIDADE_DAS_PROMOÇÕES { get; set; }
}