// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("BOOKSAP_ARQUIVOS")]
public partial class BOOKSAP_ARQUIVO
{
    [Key]
    public int ID { get; set; }

    [StringLength(350)]
    [Unicode(false)]
    public string SESSAO_BOOK { get; set; }

    [StringLength(350)]
    [Unicode(false)]
    public string NOME_ARQUIVO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string EXTENCAO_ARQUIVO { get; set; }

    public byte[] ARQUIVO { get; set; }
}