// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CADASTRO_GERENTE_TERRITORIO")]
public partial class CADASTRO_GERENTE_TERRITORIO
{
    [StringLength(255)]
    public string DDD { get; set; }

    [StringLength(255)]
    public string MATRICULA { get; set; }

    [StringLength(255)]
    public string NOME { get; set; }

    [StringLength(255)]
    public string AREA_ATUACAO_DDD { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DATA_EFETIVA_GESTAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_CADASTRO { get; set; }

    [Key]
    public int ID { get; set; }
}