// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CADASTRO_UNICO")]
public partial class CADASTRO_UNICO
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoAcesso { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Adabas { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Sexo { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Rg { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string OrgaoEmissor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataNascimento { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Rua { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Numero { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Complemento { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Bairro { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Cep { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Estado { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Celular { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Cnpj { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeContato { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string SubGrupo { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Area { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string SubArea { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Ddd { get; set; }

    public int IdAcesso { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DataSolicitacaoAdmissao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DataDemissao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DataSolicitacaoDemissao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Login { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Matricula { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Funcao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DataAdmissao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Origem { get; set; }

    [StringLength(60)]
    [Unicode(false)]
    public string PIS { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string EstadoPrestServico { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string CidadePrestServico { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string EMAILPESSOAL { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string GESTORLIDER { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string TELEFONEPESSOAL { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Regional { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Operadora { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string DataUltimaAlteracao { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Canal { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ObservacaoDesligamento { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Motivo { get; set; }

    public int? idSolicitanteDesligamento { get; set; }
}