// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CADASTROS_ROTA_GNV")]
public partial class CADASTROS_ROTA_GNV
{
    [Column("Gerente de Contas Sell Out")]
    [StringLength(255)]
    public string Gerente_de_Contas_Sell_Out { get; set; }

    [Column("CPF GNV")]
    [StringLength(255)]
    public string CPF_GNV { get; set; }

    [Column("Gerente de Negócios Varejo")]
    [StringLength(255)]
    public string Gerente_de_Negócios_Varejo { get; set; }

    public double? DDD { get; set; }

    [StringLength(255)]
    public string UF { get; set; }

    [StringLength(255)]
    public string agencia { get; set; }

    [StringLength(255)]
    public string status { get; set; }
}