// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CARTEIRA_VALIDACAO_TERRITORIAL")]
public partial class CARTEIRA_VALIDACAO_TERRITORIAL
{
    [StringLength(255)]
    public string CNPJ { get; set; }

    [Column("DATA INICIO CONTRATO", TypeName = "datetime")]
    public DateTime? DATA_INICIO_CONTRATO { get; set; }

    [Column("DATA FIM CONTRATO", TypeName = "datetime")]
    public DateTime? DATA_FIM_CONTRATO { get; set; }

    [Column("RAZÃO SOCIAL")]
    [StringLength(255)]
    public string RAZÃO_SOCIAL { get; set; }

    [Column("NOME FANTASIA")]
    [StringLength(255)]
    public string NOME_FANTASIA { get; set; }

    [Column("INSCRIÇÃO ESTADUAL")]
    [StringLength(255)]
    public string INSCRIÇÃO_ESTADUAL { get; set; }

    [Column("OPTANTE SIMPLES")]
    [StringLength(50)]
    public string OPTANTE_SIMPLES { get; set; }

    [StringLength(255)]
    public string REGIONAL { get; set; }

    [StringLength(255)]
    public string TERRITORIAL { get; set; }

    [StringLength(255)]
    public string CEP { get; set; }

    [StringLength(255)]
    public string ENDEREÇO { get; set; }

    [Column("BAIRRO ")]
    [StringLength(255)]
    public string BAIRRO_ { get; set; }

    [StringLength(255)]
    public string CIDADE { get; set; }

    [StringLength(255)]
    public string NUMERO { get; set; }

    [StringLength(255)]
    public string COMPLEMENTO { get; set; }

    [StringLength(255)]
    public string CONTATO { get; set; }

    [StringLength(255)]
    public string TELEFONE { get; set; }

    [StringLength(255)]
    public string CELULAR { get; set; }

    [StringLength(255)]
    public string FAX { get; set; }

    [Column("E-MAIL FINANCEIRO")]
    [StringLength(255)]
    public string E_MAIL_FINANCEIRO { get; set; }

    [Column("E-MAIL COMERCIAL")]
    [StringLength(255)]
    public string E_MAIL_COMERCIAL { get; set; }

    [Column("E-MAIL DIVULGAÇÃO")]
    [StringLength(255)]
    public string E_MAIL_DIVULGAÇÃO { get; set; }

    [Column("HOME PAGE")]
    [StringLength(255)]
    public string HOME_PAGE { get; set; }

    [Column("CODIGO BANCO")]
    [StringLength(255)]
    public string CODIGO_BANCO { get; set; }

    [StringLength(255)]
    public string AGENCIA { get; set; }

    [Column("NUMERO CONTA")]
    [StringLength(255)]
    public string NUMERO_CONTA { get; set; }

    [Column("DIGITO VERIFICADOR")]
    [StringLength(255)]
    public string DIGITO_VERIFICADOR { get; set; }

    [Column("REGIÃO GEOGRAFICA")]
    [StringLength(255)]
    public string REGIÃO_GEOGRAFICA { get; set; }

    [Column("SETOR ATIVIDADE")]
    [StringLength(255)]
    public string SETOR_ATIVIDADE { get; set; }

    [Column("ÁREA DE CREDITO")]
    [StringLength(255)]
    public string ÁREA_DE_CREDITO { get; set; }

    [Column("ORGANIZAÇÃO DE COMPRAS")]
    [StringLength(255)]
    public string ORGANIZAÇÃO_DE_COMPRAS { get; set; }

    [Column("ORGANIZAÇÃO DE VENDAS")]
    [StringLength(255)]
    public string ORGANIZAÇÃO_DE_VENDAS { get; set; }

    [Column("GRUPO VENDEDOR/NOME GC")]
    [StringLength(255)]
    public string GRUPO_VENDEDOR_NOME_GC { get; set; }

    [Column("PAGADOR FATURA")]
    [StringLength(255)]
    public string PAGADOR_FATURA { get; set; }

    [Column("RECEBEDOR DA MERCADORIA")]
    [StringLength(50)]
    [Unicode(false)]
    public string RECEBEDOR_DA_MERCADORIA { get; set; }

    [Column("RECEBEDOR FATURA")]
    [StringLength(255)]
    public string RECEBEDOR_FATURA { get; set; }

    [Column("CODIGO VENDEDOR")]
    [StringLength(255)]
    public string CODIGO_VENDEDOR { get; set; }

    [StringLength(255)]
    public string REGIONAL2 { get; set; }

    [StringLength(255)]
    public string TERRITORIAL2 { get; set; }

    [StringLength(255)]
    public string UF { get; set; }

    [Column("RECEBEDOR DO COMISSIONAMENTO")]
    [StringLength(255)]
    public string RECEBEDOR_DO_COMISSIONAMENTO { get; set; }

    [Column("PONTO DE VENDA")]
    [StringLength(255)]
    public string PONTO_DE_VENDA { get; set; }

    [StringLength(255)]
    public string GESTOR { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_CADASTRO_GESTOR { get; set; }

    [Column("SELL IN")]
    [StringLength(255)]
    public string SELL_IN { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_CADASTRO_SELL_IN { get; set; }

    [Column("STATUS CALLIDUS")]
    [StringLength(255)]
    public string STATUS_CALLIDUS { get; set; }

    public double? INSTANCIA { get; set; }

    [StringLength(255)]
    public string ATIVIDADE { get; set; }

    [Column(TypeName = "money")]
    public decimal? LIMITE { get; set; }

    [Column("PRAZO LIMITE", TypeName = "datetime")]
    public DateTime? PRAZO_LIMITE { get; set; }

    [Column("MARGEM APARELHO")]
    [StringLength(50)]
    [Unicode(false)]
    public string MARGEM_APARELHO { get; set; }

    [Column("MARGEM CHIP")]
    [StringLength(50)]
    [Unicode(false)]
    public string MARGEM_CHIP { get; set; }

    [Column("MARGEM  RECARGA")]
    [StringLength(50)]
    [Unicode(false)]
    public string MARGEM__RECARGA { get; set; }

    [Column("CONDIÇÕES DE PAGAMENTO")]
    [StringLength(255)]
    public string CONDIÇÕES_DE_PAGAMENTO { get; set; }

    [Column("VPC (Sell in ou Out)")]
    [StringLength(255)]
    public string VPC__Sell_in_ou_Out_ { get; set; }

    [Column("ATUAL ESTRELAGEM")]
    [StringLength(255)]
    public string ATUAL_ESTRELAGEM { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_EFETI_CART_SELL_IN { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_EFETI_CART_GESTOR { get; set; }

    [Column("CANAL DISTRIBUIÇÃO")]
    [StringLength(255)]
    public string CANAL_DISTRIBUIÇÃO { get; set; }

    [StringLength(255)]
    public string VENDEDOR { get; set; }

    [StringLength(255)]
    public string REDE { get; set; }

    [StringLength(255)]
    public string CANAL { get; set; }

    [Column("CÓDIGO CLIENTE")]
    [StringLength(50)]
    [Unicode(false)]
    public string CÓDIGO_CLIENTE { get; set; }

    [Column("CÓDIGO FORNECEDOR")]
    [StringLength(50)]
    [Unicode(false)]
    public string CÓDIGO_FORNECEDOR { get; set; }

    [StringLength(255)]
    public string MATRICULA_GER_CONTA { get; set; }

    [StringLength(255)]
    public string COD_IBGE { get; set; }

    [StringLength(255)]
    public string UF_LOCALIDADE_PDV { get; set; }

    [StringLength(255)]
    public string IXOS { get; set; }

    [Column("DDD GESTOR")]
    [StringLength(255)]
    public string DDD_GESTOR { get; set; }

    [Column("AREA ATUAÇÃO DDD GESTOR")]
    [StringLength(255)]
    public string AREA_ATUAÇÃO_DDD_GESTOR { get; set; }

    [Column("GERENTE TERRITORIAL")]
    [StringLength(255)]
    public string GERENTE_TERRITORIAL { get; set; }

    [StringLength(255)]
    public string NOVO_GESTOR { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_NOVO_GESTOR { get; set; }

    public string OBS { get; set; }

    [StringLength(15)]
    public string MES_LIBERACAO { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string NOVO_GERENTE_TERRITORIAL { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_NOVO_TERRITORIAL { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MATRICULA_SELL_IN { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MATRICULA_TERRITORIAL { get; set; }
}