// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CARTEIRA_ARMARIO_PENDENTES")]
public partial class CARTEIRA_ARMARIO_PENDENTE
{
    [StringLength(255)]
    public string GA { get; set; }

    [StringLength(60)]
    [Unicode(false)]
    public string GV { get; set; }

    [StringLength(8)]
    [Unicode(false)]
    public string ANOMES { get; set; }

    [Key]
    public int ID { get; set; }

    public int? Id_Armario { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataSolicitacao { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string idAcesso { get; set; }

    public bool? AprovacaoCanal { get; set; }

    public bool? AprovacaoDivisao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataUltimaAlteracao { get; set; }

    [StringLength(50)]
    public string MICROTERRITORIO { get; set; }

    [StringLength(50)]
    public string ARMÁRIO { get; set; }
}