// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CARTEIRA_RELACAO_PDV_COLABORADOR")]
public partial class CARTEIRA_RELACAO_PDV_COLABORADOR
{
    [StringLength(255)]
    public string Cnpj { get; set; }

    [StringLength(255)]
    public string NomeFantasia { get; set; }

    [StringLength(255)]
    public string Vendedor { get; set; }

    [StringLength(255)]
    public string REDE { get; set; }

    [StringLength(255)]
    public string Canal { get; set; }

    [StringLength(255)]
    public string Atividade { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MATRICULA_GV { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MATRICULA_GA { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MATRICULA_GGP { get; set; }
}