// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class CARTEIRA_PARCIAL_PENDENTE
{
    [StringLength(20)]
    [Unicode(false)]
    public string Divisao { get; set; }

    public int? QTD_TOTAL { get; set; }

    public int? QTD_ALTERADO { get; set; }

    public int? QTD_NAO_ALTERADOS { get; set; }
}