// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CARTEIRA_PDV")]
public partial class CARTEIRA_PDV
{
    [Key]
    public int ID { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string RAZAO_SOCIAL { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string GERENTE_CONTAS { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string DATA_EFETIVACAO { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string ADABAS { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string UF { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string CANAL { get; set; }
}