// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CARTEIRA_ARMARIO")]
public partial class CARTEIRA_ARMARIO
{
    [StringLength(255)]
    public string UF { get; set; }

    [StringLength(255)]
    public string DDD { get; set; }

    [StringLength(255)]
    public string CIDADE { get; set; }

    [StringLength(255)]
    public string ARMÁRIO { get; set; }

    [StringLength(255)]
    public string TIPO { get; set; }

    [StringLength(255)]
    public string MICROTERRITÓRIO { get; set; }

    [StringLength(255)]
    public string GA { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string DIVISAO_SIGLA { get; set; }

    [StringLength(60)]
    [Unicode(false)]
    public string GV { get; set; }

    [StringLength(60)]
    [Unicode(false)]
    public string RESP_DIVISAO { get; set; }

    [StringLength(8)]
    [Unicode(false)]
    public string ANOMES { get; set; }

    [Key]
    public int ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataUltimaAlteracao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataSolicitacao { get; set; }

    public bool? ANOMES_ATUAL { get; set; }
}