// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CHECKLIST_ROTA")]
public partial class CHECKLIST_ROTum
{
    [Key]
    public int Id { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string NomeFantasia { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Bairro { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Uf { get; set; }

    [Unicode(false)]
    public string ObsDadosPDV { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string CpfCnpjPDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string NomePDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string EnderecoPDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string BairroPDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string CidadePDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string CurvaPDV { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string QtdChipHR { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string QtdChipSKU { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string QtdChipHROutOperadoras { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string QtdChipSKUOutOperadoras { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string FaturamentoRecarga { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string ConsultaSerial { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MaterialMerchanInterno { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MaterialMerchanInternoVisivel { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MaterialMerchanInternoConcorrencia { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MaterialMerchanExterno { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MaterialMerchanExternoVisivel { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MaterialMerchanExternoConcorrencia { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string RecargaEletronicaFuncionando { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TempoRetorno { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string PdvPossuiAdesivo { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string FreqVisitaVendedor { get; set; }

    [Unicode(false)]
    public string NomePromoVigente { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string NrCadastroPromocao { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string IndiceSatisfacao { get; set; }

    public int? idAcesso { get; set; }
}