// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CHECKLIST_PEX_REVENDA_CICLO_3")]
public partial class CHECKLIST_PEX_REVENDA_CICLO_3
{
    public int ID { get; set; }

    [Unicode(false)]
    public string PONTUACAO { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string UF { get; set; }

    [Unicode(false)]
    public string RAZAO_SOCIAL { get; set; }

    [Unicode(false)]
    public string ABADAS { get; set; }

    [Unicode(false)]
    public string CNPJ { get; set; }

    [Unicode(false)]
    public string CIDADE { get; set; }

    [Unicode(false)]
    public string BAIRRO { get; set; }

    [Unicode(false)]
    public string DATA_AUDITORIA { get; set; }

    [Unicode(false)]
    public string GERENTE_PRESENTE { get; set; }

    [Unicode(false)]
    public string NOME_GERENTE { get; set; }

    [Unicode(false)]
    public string CPF_GERENTE { get; set; }

    [Unicode(false)]
    public string JUSTIFICATIVA_AUSENCIA_GERENTE { get; set; }

    [Unicode(false)]
    public string DESCRICAO_OUTRO_MOTIVO_AUSENCIA_GERENTE { get; set; }

    [Unicode(false)]
    public string AUSENCIA_GERENTE_JUSTIFICAVEL { get; set; }

    public int? PONTUACAO_GERENTE_PRESENTE { get; set; }

    [Unicode(false)]
    public string GURU_PRESENTE { get; set; }

    [Unicode(false)]
    public string NOME_GURU { get; set; }

    [Unicode(false)]
    public string CPF_GURU { get; set; }

    [Unicode(false)]
    public string LOGIN_GURU { get; set; }

    [Unicode(false)]
    public string JUSTIFICATIVA_AUSENCIA_GURU { get; set; }

    [Unicode(false)]
    public string DESCRICAO_OUTRO_MOTIVO_AUSENCIA_GURU { get; set; }

    [Unicode(false)]
    public string AUSENCIA_GURU_JUSTIFICAVEL { get; set; }

    public int? PONTUACAO_GURU_PRESENTE { get; set; }

    [Unicode(false)]
    public string EQUIPE_UNIFORMIZADA { get; set; }

    [Unicode(false)]
    public string ERRO_EQUIPE_UNIFORMIZADA { get; set; }

    public int? PONTUACAO_EQUIPE_UNIFORMIZADA { get; set; }

    [Unicode(false)]
    public string CARTAZ_ATITUDES { get; set; }

    public int? PONTUACAO_CARTAZ_ATITUDES { get; set; }

    [Unicode(false)]
    public string GERENTE_POSSUI_ACESSO_VIVO_360 { get; set; }

    [Unicode(false)]
    public string LOGIN_GERENTE_VIVO_360 { get; set; }

    public int? PONTUACAO_GERENTE_POSSUI_ACESSO_VIVO_360 { get; set; }

    [Unicode(false)]
    public string ACESSO_ATLYS { get; set; }

    public int? PONTUACAO_ACESSO_ATLYS { get; set; }

    [Unicode(false)]
    public string ACESSO_360 { get; set; }

    public int? PONTUACAO_ACESSO_360 { get; set; }

    [Unicode(false)]
    public string ACESSO_NSIA { get; set; }

    public int? PONTUACAO_ACESSO_NSIA { get; set; }

    [Unicode(false)]
    public string ACESSO_WEB_VENDAS { get; set; }

    public int? PONTUACAO_ACESSO_WEB_VENDAS { get; set; }

    [Unicode(false)]
    public string ACESSO_KIPON { get; set; }

    public int? PONTUACAO_ACESSO_KIPON { get; set; }

    [Unicode(false)]
    public string ACESSO_TREINAPP { get; set; }

    public int? PONTUACAO_ACESSO_TREINAPP { get; set; }

    [Unicode(false)]
    public string FACHADA_PADRONIZADA { get; set; }

    public int? PONTUACAO_FACHADA_PADRONIZADA { get; set; }

    [Unicode(false)]
    public string LOGO_LUMINOSO { get; set; }

    public int? PONTUACAO_LOGO_LUMINOSO { get; set; }

    [Unicode(false)]
    public string SOLEIRA_LOJA { get; set; }

    [Unicode(false)]
    public string PORTICO { get; set; }

    [Unicode(false)]
    public string POSSUI_ICONE { get; set; }

    [Unicode(false)]
    public string ICONE_INSTALADO_PADRAO { get; set; }

    public int? PONTUACAO_ICONE { get; set; }

    public int? PONTUACAO_INSTALACAO_ICONE { get; set; }

    [Unicode(false)]
    public string ADESIVO_ANTIROMBADA { get; set; }

    public int? PONTUACAO_ADESIVO_ANTIROMBADA { get; set; }

    [Unicode(false)]
    public string ADESIVO_HORARIO_FUNC { get; set; }

    public int? PONTUACAO_ADESIVO_HORARIO_FUNC { get; set; }

    [Unicode(false)]
    public string PAREDE_PADRONIZADA { get; set; }

    [Unicode(false)]
    public string PAREDE_PADRONIZADA_STENCIL { get; set; }

    public int? PONTUACAO_PAREDE_PADRONIZADA { get; set; }

    [Unicode(false)]
    public string PISO_PADRONIZADO { get; set; }

    public int? PONTUACAO_PISO_PADRONIZADO { get; set; }

    [Unicode(false)]
    public string TAV_FUNCIONANDO { get; set; }

    [Unicode(false)]
    public string EXISTE_CHAMADO_TAV { get; set; }

    [Unicode(false)]
    public string NUM_CHAMADO_TAV { get; set; }

    public int? PONTUACAO_TAV_FUNCIONANDO { get; set; }

    [Unicode(false)]
    public string GSS_FUNCIONANDO { get; set; }

    [Unicode(false)]
    public string EXISTE_CHAMADO_GSS { get; set; }

    [Unicode(false)]
    public string NUM_CHAMADO_GSS { get; set; }

    public int? PONTUACAO_GSS_FUNCIONANDO { get; set; }

    [Unicode(false)]
    public string MODULO_SVA { get; set; }

    public int? PONTUACAO_MODULO_SVA { get; set; }

    [Unicode(false)]
    public string MESA_DEGUSTACAO { get; set; }

    [Unicode(false)]
    public string PAINEL_ACC { get; set; }

    [Unicode(false)]
    public string PRECIFICACAO_PRODUTOS { get; set; }

    [Unicode(false)]
    public string WALL_TESTEIRA { get; set; }

    [Unicode(false)]
    public string POSSUI_URNA_COLETORA { get; set; }

    [Unicode(false)]
    public string MATERIAL_URNA { get; set; }

    [Unicode(false)]
    public string OUTRO_MATERIAL_URNA { get; set; }

    public int? PONTUACAO_POSSUI_URNA_COLETORA { get; set; }

    [Unicode(false)]
    public string ESPACO_TV { get; set; }

    [Unicode(false)]
    public string ADESIVO_CARREGUE_AQUI { get; set; }

    [Unicode(false)]
    public string MOSAICO_TV { get; set; }

    [Unicode(false)]
    public string COMUNICACAO_MOSAICO_TV { get; set; }

    [Unicode(false)]
    public string PUFF { get; set; }

    [Unicode(false)]
    public string GIGANTOGRAFIA { get; set; }

    [Unicode(false)]
    public string ADESIVO_PREMIUM_GERENTE { get; set; }

    [Unicode(false)]
    public string MESA_BANCADA { get; set; }

    [Unicode(false)]
    public string ESPACO_GURU { get; set; }

    [Unicode(false)]
    public string BANQUETAS { get; set; }

    [Unicode(false)]
    public string MOBILIARIO_LOJA { get; set; }

    public int? PONTUACAO_MOBILIARIO_LOJA { get; set; }

    [Unicode(false)]
    public string LIXEIRAS_PADRONIZADAS { get; set; }

    public int? PONTUACAO_LIXEIRAS_PADRONIZADAS { get; set; }

    [Unicode(false)]
    public string ILUMINACAO_AGRADAVEL { get; set; }

    [Unicode(false)]
    public string LAMPADA_QUEIMADA { get; set; }

    public int? PONTUACAO_ILUMINACAO_AGRADAVEL { get; set; }

    public int? PONTUACAO_LAMPADA_QUEIMADA { get; set; }

    [Unicode(false)]
    public string EXISTE_POLUICAO_VIS_LOJA { get; set; }

    public int? PONTUACAO_EXISTE_POLUICAO_VIS_LOJA { get; set; }

    [Unicode(false)]
    public string COMUNICACAO_LEGAL { get; set; }

    public int? PONTUACAO_COMUNICACAO_LEGAL { get; set; }

    [Unicode(false)]
    public string ADESIVO_PA { get; set; }

    public int? PONTUACAO_ADESIVO_PA { get; set; }

    [Unicode(false)]
    public string VITRINE_EXTERNA_POSITIVADA { get; set; }

    public int? PONTUACAO_VITRINE_EXTERNA_POSITIVADA { get; set; }

    [Unicode(false)]
    public string VITRINE_INTERNA_POSITIVADA { get; set; }

    public int? PONTUACAO_VITRINE_INTERNA_POSITIVADA { get; set; }

    [Unicode(false)]
    public string AREA_ESPERA_POSITIVADA { get; set; }

    public int? PONTUACAO_AREA_ESPERA_POSITIVADA { get; set; }

    [Unicode(false)]
    public string AREA_ATEND_POSITIVADA { get; set; }

    public int? PONTUACAO_AREA_ATEND_POSITIVADA { get; set; }

    [Unicode(false)]
    public string VELOCIDADE_INTERNET { get; set; }

    public int? PONTUACAO_VELOCIDADE_INTERNET { get; set; }

    public int? SCORE { get; set; }

    public int? ID_ACESSO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_CRIACAO { get; set; }
}