// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CHECKLIST_PEX_LLPP_INFORMATIVA")]
public partial class CHECKLIST_PEX_LLPP_INFORMATIVA
{
    [Key]
    public int Id { get; set; }

    public int IdVisita { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EquipamentoTAVFuncionandoCorretamenteChamado { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EquipamentoGssFuncionandoCorretamenteChamado { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string ArCondicionadoFuncionandoChamado { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LojaLampadasFuncionandoChamado { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string TvDivulgacaoVinhetasFuncionandoChamado { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string TvInformeSenhaAtendimentoFuncionandoChamado { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LojaPossuiUrnaColetoraPadronizadaMaterialMaterial { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string MobiliarioPerfeitoEstadoChamado { get; set; }
}