// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CHECKLIST_PDR")]
public partial class CHECKLIST_PDR
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CPF { get; set; }

    [Unicode(false)]
    public string NOME_FANTASIA { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string BAIRRO { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string CIDADE { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string UF { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string DATA_VISITA { get; set; }

    [Unicode(false)]
    public string OBSERVACAO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string SEGMENTACAO_PDV { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string INFORME_SEGMENTACAO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string DISTRIBUIDOR_ATENDE { get; set; }

    [Unicode(false)]
    public string NOME_ENTREVISTADO { get; set; }

    [Unicode(false)]
    public string CARGO_ENTREVISTADO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string TRABALHA_RECARGA_ELETRONICA_VIVO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string RECARGA_ELETRONICA_VIVO_FUNCIONA { get; set; }

    [Unicode(false)]
    public string OBSERVACAO_RECARGA_ELETRONICA_VIVO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string TRABALHA_RECARGA_ELETRONICA_CONCORRENCIA { get; set; }

    [Unicode(false)]
    public string RECARGA_ELETRONICA_CONCORRENCIA { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string TRABALHA_CHIP_VIVO { get; set; }

    [Unicode(false)]
    public string VALOR_CHIP_VIVO_PARA_CLIENTE { get; set; }

    [Unicode(false)]
    public string UNIDADE_DISPONIVEL_CHIP_VIVO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string TRABALHA_CHIP_TURBINADO_VIVO { get; set; }

    [Unicode(false)]
    public string UNIDADE_COMBO_TURBINADO { get; set; }

    [Unicode(false)]
    public string VALOR_COMBO_CLIENTE_FINAL { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string VENDE_CHIP_CONCORRENCIA { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string VENDE_CHIP_TIM { get; set; }

    [Unicode(false)]
    public string VALOR_CHIP_TIM { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string VENDE_CHIP_CLARO { get; set; }

    [Unicode(false)]
    public string VALOR_CHIP_CLARO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string VENDE_CHIP_OI { get; set; }

    [Unicode(false)]
    public string VALOR_CHIP_OI { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string VENDE_COMBO_CONCORRENCIA { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string VENDE_COMBO_TIM { get; set; }

    [Unicode(false)]
    public string VALOR_COMBO_TIM { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string VENDE_COMBO_CLARO { get; set; }

    [Unicode(false)]
    public string VALOR_COMBO_CLARO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string VENDE_COMBO_OI { get; set; }

    [Unicode(false)]
    public string VALOR_COMBO_OI { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string VENDE_COMBO_OUTROS { get; set; }

    [Unicode(false)]
    public string VALOR_COMBO_OUTROS { get; set; }

    [Unicode(false)]
    public string OBSERVACOES_ABASTECIMENTO { get; set; }

    [Unicode(false)]
    public string HORAS_RESOLUCAO_DISTRIBUIDOR { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string PDV_POSSUI_CONTATO_VENDEDOR { get; set; }

    [Unicode(false)]
    public string FREQUENCIA_VISITA_VENDEDOR { get; set; }

    [Unicode(false)]
    public string OBSERVACAO_FREQUENCIA_VISITA_VENDEDOR { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string RESPONSAVEL_INFORMA_NUMERO_CADASTRO { get; set; }

    [Unicode(false)]
    public string NUMERO_CADASTRO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string RESPONSAVEL_INFORMA_NOME_PROMOCAO { get; set; }

    [Unicode(false)]
    public string NOME_PROMOCAO { get; set; }

    public int? SATISFACAO_VENDEDOR { get; set; }

    [Unicode(false)]
    public string OBSERVACAO_ORIENTACAO_PDV { get; set; }

    [Unicode(false)]
    public string POSITIVACAO_MATERIAL_MERCHANDISING { get; set; }

    [Unicode(false)]
    public string MATERIAL_INTERNO_CONCORRENCIA { get; set; }

    [Unicode(false)]
    public string OPERADORAS_MATERIAIS_INTERNO { get; set; }

    [Unicode(false)]
    public string MATERIAL_VIVO_VIGENTE_INTERNO { get; set; }

    [Unicode(false)]
    public string MATERIAL_EXTERNO_CONCORRENCIA { get; set; }

    [Unicode(false)]
    public string OPERADORAS_MATERIAIS_EXTERNO { get; set; }

    [Unicode(false)]
    public string MATERIAL_VIVO_VIGENTE_EXTERNO { get; set; }

    [Unicode(false)]
    public string OBSERVACAO_MERCHANDISING { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ADABAS { get; set; }
}