// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CHECKLIST_PDR_INTERNO")]
public partial class CHECKLIST_PDR_INTERNO
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CPF { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string NOME_FANTASIA { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string BAIRRO { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string CIDADE { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string UF { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string DATA_AUDITORIA { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string REALIZADA { get; set; }

    [Unicode(false)]
    public string MOTIVO { get; set; }

    [Unicode(false)]
    public string OBSERVACAO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string QTD_VENDEDOR_DISTRIBUIDOR { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string QTD_SUPERV_COORD_DISTRIBUIDOR { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string QTD_GERENTE_DISTRIBUIDOR { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string CALL_CENTER_ALOC_UNID_AUDIT { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string LOCAL_CALL_CENTER { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string FOTO_DATADA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QTD_ATEND_SUP_CALL_DISTR { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DISTR_POSSUI_ESTR_ATEND_ATIVO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DISTR_POSSUI_REG_CLT_CONTR_VEND { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DISTR_POSSUI_SAL_VEND_AUDIT { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QTD_CADEIRAS_SAL_VENDAS { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string CAD_SAL_VEND { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string VEND_KIT_VENDAS_COMPL { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string FORC_VENDAS_UNIFORME_PADRAO { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string COR_UNIFORME { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string OUTRA_COR_UNIFORME { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_PAREDE_PAINEL_SAL_VENDAS { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_POSSUI_SIMUL_PDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_POSSUI_QUADRO_GEST { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string OBS_DISTR_POSSUI_QUADRO_GEST { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_POSSUI_ESTR_ADEQ_MERCHAN { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_POSSUI_ESTR_ADEQ_PROD_FIS { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_POSSUI_ESTR_ADEQ_POS { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string POSSUI_50_POS_DISP { get; set; }

    [Unicode(false)]
    public string OBS_POSSUI_50_POS_DISP { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_POSSUI_FERRAM_AUX_VENDA { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_POSSUI_SIST_ROTA { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_POSSUI_APP_PISTOL_FISICO { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_ENTR_TODA_MERC_FIS { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string SIST_GEST_DISTR_IDENT_CONTR_REL_SER { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string SIST_DISTR_REC_INFORM_PED_AUTOM_VENDAS { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string VEND_CHECK_IN_PDR_AUT_VENDA { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string VEND_IND_AUT_VENDA_EST_PDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string VEND_LANCA_AUT_VENDA_ENT_SAI_MERC { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string VEND_CONS_PIST_SER_CHIP { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string VEND_CONS_PIST_SER_CARTAO_FISICO { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string SIST_GEST_DISTR_INF_VENDA_DATA { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string IDENT_EST_CHIP_PDR { get; set; }

    [Unicode(false)]
    public string OBS_IDENT_EST_CHIP_PDR { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DISTR_REG_FREQ_VIS { get; set; }

    [Unicode(false)]
    public string OBS_CRACHA { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MAT_REALIZADA { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MOM_MATIN_QTD_VEND { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string QTD_VEND_ALOC_UNID_AUDIT { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CNPJ_2 { get; set; }

    [Unicode(false)]
    public string BAIRRO_2 { get; set; }

    [Unicode(false)]
    public string CIDADE_2 { get; set; }

    [Unicode(false)]
    public string RAZAO_SOCIAL_2 { get; set; }

    public int? IDACESSO { get; set; }
}