// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CHECKLIST_PDR_EXTERNO_IMAGENS")]
public partial class CHECKLIST_PDR_EXTERNO_IMAGEN
{
    [Key]
    public int id { get; set; }

    public int idCheckListExterno { get; set; }

    public byte[] Arquivo { get; set; }

    [Unicode(false)]
    public string NomeArquivo { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ExtensaoArquivo { get; set; }

    [ForeignKey("idCheckListExterno")]
    [InverseProperty("CHECKLIST_PDR_EXTERNO_IMAGENs")]
    public virtual CHECKLIST_PDR_EXTERNO idCheckListExternoNavigation { get; set; }
}