// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CHECKLIST_PEX_LLPP_COMPROBATORIA")]
public partial class CHECKLIST_PEX_LLPP_COMPROBATORIum
{
    [Key]
    public int Id { get; set; }

    public int IdVisita { get; set; }

    public byte[] EquipamentoFuncionandoCorretamenteFoto { get; set; }

    public byte[] EquipamentoGssFuncionandoCorretamenteFoto { get; set; }

    public byte[] LojaLampadasFuncionandoFoto { get; set; }

    public byte[] TvDivulgacaoVinhetasFuncionandoFoto { get; set; }

    public byte[] TvInformeSenhaAtendimentoFuncionandoFoto { get; set; }

    public byte[] FachadaLojaPadronizadaFoto { get; set; }

    public byte[] PisoLojaPadronizadoFoto { get; set; }

    public byte[] ParedeLojaPadronizadaFoto { get; set; }

    public byte[] CadeirasLojaPadronizadaFoto { get; set; }

    public byte[] LixeiraLojaPadronizadaFoto { get; set; }

    public byte[] LojaPossuiUrnaColetoraPadronizadaFoto { get; set; }

    public byte[] MobiliarioPerfeitoEstadoFoto { get; set; }

    public byte[] FiacaoExpostaFormaOrdenadaNaoVisivelClienteFoto { get; set; }

    public byte[] MaquinasUsamChipVivoFoto { get; set; }

    public byte[] LojaPossuiRevistaMundoVivoVersaoDigitalFoto { get; set; }

    public byte[] LojaPossuiCodigoDefesaConsumidorFoto { get; set; }

    public byte[] VitrineExternaPositivadaMapaPdvFoto { get; set; }

    public byte[] VitrineInternaDegustadoresPositivadosFoto { get; set; }

    public byte[] AreaAcessoLojaPositivadaFoto { get; set; }

    public byte[] AreaEsperaEstaPositivadaFoto { get; set; }

    public byte[] AreaAtendimentoPositivadaFoto { get; set; }

    public byte[] AparelhosLigadosVinhetasAprovadasFoto { get; set; }

    public byte[] DisplaysAparelhosemonstraçãoFoto { get; set; }

    public byte[] CaixaLojaCorretoFoto { get; set; }

    public byte[] FechamentoFinanceiroDiaAnteriorFechouSemPendenciaFoto { get; set; }

    public byte[] LlojaEstaAreasSalaoVendasFoto { get; set; }

    public byte[] MetasEstaoExpostasFoto { get; set; }

    public byte[] PAEscolhidaArvoreOfertasInstaladaFoto { get; set; }
}