// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CHECKLIST_PDR_INTERNO_ARQUIVOS")]
public partial class CHECKLIST_PDR_INTERNO_ARQUIVO
{
    [Key]
    public int ID { get; set; }

    public int? ID_CHECKLIST_PDR_INTERNO { get; set; }

    [Unicode(false)]
    public string NOME_CAMPO { get; set; }

    public byte[] ARQUIVO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string EXT_ARQUIVO { get; set; }
}