// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CHECKLIST_PEX_REVENDA")]
public partial class CHECKLIST_PEX_REVENDum
{
    public int ID { get; set; }

    [Unicode(false)]
    public string LAUDA { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string UF { get; set; }

    [Unicode(false)]
    public string RAZAO_SOCIAL { get; set; }

    [Unicode(false)]
    public string ABADAS { get; set; }

    [Unicode(false)]
    public string CNPJ { get; set; }

    [Unicode(false)]
    public string CIDADE { get; set; }

    [Unicode(false)]
    public string BAIRRO { get; set; }

    [Unicode(false)]
    public string DATA_AUDITORIA { get; set; }

    [Unicode(false)]
    public string GERENTE_PRESENTE { get; set; }

    public int? PONTUACAO_GERENTE_PRESENTE { get; set; }

    [Unicode(false)]
    public string NOME_GERENTE { get; set; }

    [Unicode(false)]
    public string CPF_GERENTE { get; set; }

    [Unicode(false)]
    public string JUSTIFICATIVA_AUSENCIA_GERENTE { get; set; }

    [Unicode(false)]
    public string MOTIVO_AUSENCIA_GERENTE { get; set; }

    [Unicode(false)]
    public string AUSENCIA_GERENTE_JUSTIFICAVEL { get; set; }

    [Unicode(false)]
    public string GERENTE_POSSUI_ACESSO_VIVO_360 { get; set; }

    public int? PONTUACAO_GERENTE_POSSUI_ACESSO_VIVO_360 { get; set; }

    [Unicode(false)]
    public string LOGIN_GERENTE_VIVO_360 { get; set; }

    public int? QTD_VENDEDORES_LOJA { get; set; }

    [Unicode(false)]
    public string NOME_VEND_1 { get; set; }

    [Unicode(false)]
    public string CPF_VEND_1 { get; set; }

    [Unicode(false)]
    public string LOGIN_VIVO_360_VEND_1 { get; set; }

    [Unicode(false)]
    public string NOME_VEND_2 { get; set; }

    [Unicode(false)]
    public string CPF_VEND_2 { get; set; }

    [Unicode(false)]
    public string LOGIN_VIVO_360_VEND_2 { get; set; }

    [Unicode(false)]
    public string NOME_VEND_3 { get; set; }

    [Unicode(false)]
    public string CPF_VEND_3 { get; set; }

    [Unicode(false)]
    public string LOGIN_VIVO_360_VEND_3 { get; set; }

    [Unicode(false)]
    public string VENDEDORES_POSSUEM_ACESSO_VIVO_360 { get; set; }

    public int? PONTUACAO_VENDEDORES_POSSUEM_ACESSO_VIVO_360 { get; set; }

    [Unicode(false)]
    public string GURU_PRESENTE { get; set; }

    public int? PONTUACAO_GURU_PRESENTE { get; set; }

    [Unicode(false)]
    public string NOME_GURU { get; set; }

    [Unicode(false)]
    public string CPF_GURU { get; set; }

    [Unicode(false)]
    public string LOGIN_VIVO_360_GURU { get; set; }

    [Unicode(false)]
    public string JUST_AUS_GURU { get; set; }

    [Unicode(false)]
    public string MOTIVO_AUS_GURU { get; set; }

    [Unicode(false)]
    public string AUSENCIA_JUSTIFICAVEL_GURU { get; set; }

    [Unicode(false)]
    public string EQUIPE_UNIFORMIZADA { get; set; }

    public int? PONTUACAO_EQUIPE_UNIFORMIZADA { get; set; }

    [Unicode(false)]
    public string EXISTE_PROMOTOR_FABRICANTE { get; set; }

    [Unicode(false)]
    public string VITRINE_EXTERNA_POSITIVADA { get; set; }

    public int? PONTUACAO_VITRINE_EXTERNA_POSITIVADA { get; set; }

    [Unicode(false)]
    public string VITRINE_INTERNA_POSITIVADA { get; set; }

    public int? PONTUACAO_VITRINE_INTERNA_POSITIVADA { get; set; }

    [Unicode(false)]
    public string AREA_ACESSO_POSITIVADA { get; set; }

    public int? PONTUACAO_AREA_ACESSO_POSITIVADA { get; set; }

    [Unicode(false)]
    public string AREA_ESPERA_POSITIVADA { get; set; }

    public int? PONTUACAO_AREA_ESPERA_POSITIVADA { get; set; }

    [Unicode(false)]
    public string AREA_ATEND_POSITIVADA { get; set; }

    public int? PONTUACAO_AREA_ATEND_POSITIVADA { get; set; }

    [Unicode(false)]
    public string EXISTE_POLUICAO_VIS_LOJA { get; set; }

    public int? PONTUACAO_EXISTE_POLUICAO_VIS_LOJA { get; set; }

    [Unicode(false)]
    public string DISPLAYS_LOJA { get; set; }

    public int? PONTUACAO_DISPLAYS_LOJA { get; set; }

    [Unicode(false)]
    public string FACHADA_PADRONIZADA { get; set; }

    public int? PONTUACAO_FACHADA_PADRONIZADA { get; set; }

    [Unicode(false)]
    public string PISO_PADRONIZADO { get; set; }

    public int? PONTUACAO_PISO_PADRONIZADO { get; set; }

    [Unicode(false)]
    public string PAREDE_PADRONIZADA { get; set; }

    public int? PONTUACAO_PAREDE_PADRONIZADA { get; set; }

    [Unicode(false)]
    public string CADEIRAS_PADRONIZADAS { get; set; }

    public int? PONTUACAO_CADEIRAS_PADRONIZADAS { get; set; }

    [Unicode(false)]
    public string LIXEIRAS_PADRONIZADAS { get; set; }

    public int? PONTUACAO_LIXEIRAS_PADRONIZADAS { get; set; }

    [Unicode(false)]
    public string LAMPADAS_FUNCIONANDO { get; set; }

    public int? PONTUACAO_LAMPADAS_FUNCIONANDO { get; set; }

    [Unicode(false)]
    public string AR_COND_LIGADO { get; set; }

    public int? PONTUACAO_AR_COND_LIGADO { get; set; }

    [Unicode(false)]
    public string TAV_FUNCIONANDO { get; set; }

    [Unicode(false)]
    public string EXISTE_CHAMADO_TAV { get; set; }

    [Unicode(false)]
    public string NUM_CHAMADO_TAV { get; set; }

    public int? PONTUACAO_TAV_FUNCIONANDO { get; set; }

    [Unicode(false)]
    public string GSS_FUNCIONANDO { get; set; }

    [Unicode(false)]
    public string EXISTE_CHAMADO_GSS { get; set; }

    [Unicode(false)]
    public string NUM_CHAMADO_GSS { get; set; }

    public int? PONTUACAO_GSS_FUNCIONANDO { get; set; }

    [Unicode(false)]
    public string LOJA_LIMPA { get; set; }

    public int? PONTUACAO_LOJA_LIMPA { get; set; }

    [Unicode(false)]
    public string MOBILIARIO_LOJA { get; set; }

    public int? PONTUACAO_MOBILIARIO_LOJA { get; set; }

    [Unicode(false)]
    public string MOBILIARIO_FABRICANTE { get; set; }

    public int? PONTUACAO_POSSUI_MOBILIARIO_FABRICANTE { get; set; }

    [Unicode(false)]
    public string POSSUI_URNA_COLETORA { get; set; }

    [Unicode(false)]
    public string MATERIAL_URNA { get; set; }

    [Unicode(false)]
    public string OUTRO_MATERIAL_URNA { get; set; }

    public int? PONTUACAO_POSSUI_URNA_COLETORA { get; set; }

    [Unicode(false)]
    public string POSSUI_PC_TABLET { get; set; }

    [Unicode(false)]
    public string POSSUI_IMPRESSORA { get; set; }

    [Unicode(false)]
    public string POSSUI_SCANNER { get; set; }

    [Unicode(false)]
    public string POSSUI_TEL_1058 { get; set; }

    [Unicode(false)]
    public string NUM_TEL_1058 { get; set; }

    [Unicode(false)]
    public string POSSUI_PIN_PAD { get; set; }

    [Unicode(false)]
    public string POSSUI_PISTOLA_LEITURA { get; set; }

    [Unicode(false)]
    public string POSSUI_COD_DEF_CONS { get; set; }

    public int? PONTUACAO_POSSUI_MATERIAIS_BASICOS { get; set; }

    [Unicode(false)]
    public string VELOCIDADE_INTERNET { get; set; }

    public int? PONTUACAO_VELOCIDADE_INTERNET { get; set; }

    [Unicode(false)]
    public string PA_ARVORE_OFERTA { get; set; }

    public int? PONTUACAO_PA_ARVORE_OFERTA { get; set; }

    [Unicode(false)]
    public string VIVO_360_OK { get; set; }

    [Unicode(false)]
    public string MOTIVO_FALHA_VIVO_OK { get; set; }

    public int? PONTUACAO_VIVO_360_OK { get; set; }

    [Unicode(false)]
    public string VIVO_GED_OK { get; set; }

    [Unicode(false)]
    public string MOTIVO_FALHA_VIVO_GED { get; set; }

    public int? PONTUACAO_VIVO_GED_OK { get; set; }

    [Unicode(false)]
    public string EMISSAO_SENHA_GSS { get; set; }

    public int? PONTUACAO_EMISSAO_SENHA_GSS { get; set; }

    [Unicode(false)]
    public string QUADRO_GESTAO { get; set; }

    public int? PONTUACAO_QUADRO_GESTAO { get; set; }

    [Unicode(false)]
    public string CAPACITACAO { get; set; }

    public int? PONTUACAO_CAPACITACAO { get; set; }

    [Unicode(false)]
    public string ALTAS_MIGRAS { get; set; }

    public int? PONTUACAO_ALTAS_MIGRAS { get; set; }

    [Unicode(false)]
    public string TROCA_CHIP { get; set; }

    public int? PONTUACAO_TROCA_CHIP { get; set; }

    [Unicode(false)]
    public string TROCA_PLANO { get; set; }

    public int? PONTUACAO_TROCA_PLANO { get; set; }

    public int? SCORE { get; set; }

    public int? ID_ACESSO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_CRIACAO { get; set; }
}