// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CHECKLIST_PEX_CICLO_2_ARQUIVOS")]
public partial class CHECKLIST_PEX_CICLO_2_ARQUIVO
{
    public int ID { get; set; }

    public int ID_CHECKLIST_PEX { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ADABA { get; set; }

    [Unicode(false)]
    public string NOME_CAMPO { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string DATA_AUDITORIA { get; set; }

    public byte[] ARQUIVO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string EXT_ARQUIVO { get; set; }
}