// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CHECKLIST_PEX_LLPP_2")]
public partial class CHECKLIST_PEX_LLPP_2
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string Ddd { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string Loja { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string TipoLoja { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Data { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataCadastro { get; set; }

    public int IdAcesso { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Nota { get; set; }

    [ForeignKey("IdAcesso")]
    [InverseProperty("CHECKLIST_PEX_LLPP_2s")]
    public virtual ACESSO IdAcessoNavigation { get; set; }
}