// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CHECKLIST_PDR_EXTERNO")]
public partial class CHECKLIST_PDR_EXTERNO
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Adabas { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string DataVisita { get; set; }

    public string Obs { get; set; }

    [StringLength(255)]
    public string SegmentacaodoPdvCorreta { get; set; }

    [StringLength(255)]
    public string SegmentacaodoPdvCorretaQual { get; set; }

    [StringLength(255)]
    public string DistribuidorAtendePdvInformado { get; set; }

    [StringLength(255)]
    public string NomeCompletoEntrevistado { get; set; }

    [StringLength(255)]
    public string CargoEntrevistado { get; set; }

    public string ObsSobreDadosPdvObs { get; set; }

    [StringLength(255)]
    public string PdvTrabalhaRecargaEletronicavivo { get; set; }

    public string PdvTrabalhaRecargaEletronicavivoOBSObs { get; set; }

    [StringLength(255)]
    public string RecargaEletronicavivoFuncionandocorretamente { get; set; }

    public string RecargaEletronicavivoFuncionandocorretamenteOBSObs { get; set; }

    [StringLength(255)]
    public string PdvTrabalhaRecargaEletronicadaConcorrencia { get; set; }

    [StringLength(255)]
    public string QuaisRecargasEletronicasConcorrencia { get; set; }

    [StringLength(255)]
    public string PdvTrabalhaComChipVivo { get; set; }

    [StringLength(255)]
    public string QualValorVivoChipPraticadoPdvCliente { get; set; }

    [StringLength(255)]
    public string QuantasUnidadesChipVivoDisponivel { get; set; }

    [StringLength(255)]
    public string PdvTrabalhaComCombo { get; set; }

    [StringLength(255)]
    public string QuantasUnidadesCombo { get; set; }

    [StringLength(255)]
    public string QualValorComboPraticadoCliente { get; set; }

    [StringLength(255)]
    public string PdvVendeChipConcorrencia { get; set; }

    [StringLength(255)]
    public string VendeChipTim { get; set; }

    [StringLength(255)]
    public string ValorChipTim { get; set; }

    [StringLength(255)]
    public string VendeChipOi { get; set; }

    [StringLength(255)]
    public string ValorChipOi { get; set; }

    [StringLength(255)]
    public string VendeChipClaro { get; set; }

    [StringLength(255)]
    public string ValorChipClaro { get; set; }

    [StringLength(255)]
    public string PdvVendeCombo { get; set; }

    [StringLength(255)]
    public string VendeComboTim { get; set; }

    [StringLength(255)]
    public string ValorComboTim { get; set; }

    [StringLength(255)]
    public string VendeComboClaro { get; set; }

    [StringLength(255)]
    public string ValorComboClaro { get; set; }

    [StringLength(255)]
    public string VendeComboOi { get; set; }

    [StringLength(255)]
    public string QualoValorComboOi { get; set; }

    public string ObsSobreAbastecimentoObs { get; set; }

    [StringLength(255)]
    public string ReposicaoConserto { get; set; }

    [StringLength(255)]
    public string responsAvelPeloPdvPossuioContatovendedor { get; set; }

    [StringLength(255)]
    public string frequenciaVisitaVendedor { get; set; }

    [StringLength(255)]
    public string NumeroCadastroPromocao { get; set; }

    [StringLength(255)]
    public string NCadastro { get; set; }

    [StringLength(255)]
    public string ResponsavelPromocaoVigente { get; set; }

    [StringLength(255)]
    public string NomePromocao { get; set; }

    [StringLength(255)]
    public string ZeroDezIndicadeSatisfacao { get; set; }

    public string ObsSobreOrientacaoPDvObs { get; set; }

    [StringLength(255)]
    public string MerchandisingInterna { get; set; }

    [StringLength(255)]
    public string MaterialInternoConcorrencia { get; set; }

    [StringLength(255)]
    public string QuaisOperadorasMaterialInterno { get; set; }

    [StringLength(255)]
    public string PdvPossuiMaterialVigenteInterno { get; set; }

    [StringLength(255)]
    public string PdvPossuiMaterialExterno { get; set; }

    [StringLength(255)]
    public string PdvPossuiMaterialExternoConcorrencia { get; set; }

    [StringLength(255)]
    public string PdvPossuiMaterialVigenteExterno { get; set; }

    public string ObsSobreMerchandisingObs { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string idAcesso { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Cnpj_2 { get; set; }

    [Unicode(false)]
    public string Bairro_2 { get; set; }

    [Unicode(false)]
    public string Cidade_2 { get; set; }

    [Unicode(false)]
    public string RazaoSocial_2 { get; set; }

    [InverseProperty("idCheckListExternoNavigation")]
    public virtual ICollection<CHECKLIST_PDR_EXTERNO_IMAGEN> CHECKLIST_PDR_EXTERNO_IMAGENs { get; set; } = new List<CHECKLIST_PDR_EXTERNO_IMAGEN>();
}