// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class CNS_CARTEIRA_NE
{
    [StringLength(255)]
    public string VENDEDOR { get; set; }

    [StringLength(255)]
    public string UF { get; set; }

    [StringLength(255)]
    public string REDE { get; set; }

    public double? DDD_LOCALIDADE_PDV { get; set; }

    [StringLength(128)]
    [Unicode(false)]
    public string ANOMES { get; set; }
}