// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class CNS_BOLETA_UPGRADE
{
    public int IdVenda { get; set; }

    public int? DIA { get; set; }

    [Column("Data Completo Cadastro", TypeName = "datetime")]
    public DateTime? Data_Completo_Cadastro { get; set; }

    [Column("Data Cadastro", TypeName = "datetime")]
    public DateTime? Data_Cadastro { get; set; }

    [Required]
    [Column("HH:MM")]
    [StringLength(14)]
    [Unicode(false)]
    public string HH_MM { get; set; }

    [StringLength(13)]
    [Unicode(false)]
    public string LinhaUpgrade { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? ValorUpgrade { get; set; }

    [Unicode(false)]
    public string PlanoAnterior { get; set; }

    [Unicode(false)]
    public string ProtocoloGed { get; set; }

    [Unicode(false)]
    public string MaiorMenor120Dias { get; set; }
}