// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class CNS_BOLETA_TRIAGEM
{
    [StringLength(10)]
    [Unicode(false)]
    public string SENHA { get; set; }

    public int? DIA { get; set; }

    [Required]
    [StringLength(14)]
    [Unicode(false)]
    public string HHMM { get; set; }

    [StringLength(5)]
    public string Ddd { get; set; }

    [StringLength(5)]
    public string Uf { get; set; }

    [Required]
    [StringLength(8)]
    [Unicode(false)]
    public string TERRITORIO { get; set; }

    public int? TOTAL { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string CLIENTE_VIVO { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string POSSUI_COBERTURA_FIXA_VIVO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_TRIAGEM { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string LOJA { get; set; }

    [Unicode(false)]
    public string PRODUTO { get; set; }

    [Unicode(false)]
    public string CATEGORIA { get; set; }

    [Unicode(false)]
    public string CONCORRENCIA { get; set; }

    [StringLength(590)]
    [Unicode(false)]
    public string CHAVE { get; set; }
}