// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class CNS_BOLETA_NAO_VENDum
{
    public int IDVENDA { get; set; }

    public int? DIA { get; set; }

    [Column("DATA COMPLETO CADASTRO", TypeName = "datetime")]
    public DateTime? DATA_COMPLETO_CADASTRO { get; set; }

    [Column("DATA CADASTRO", TypeName = "datetime")]
    public DateTime? DATA_CADASTRO { get; set; }

    [Required]
    [Column("HH:MM")]
    [StringLength(14)]
    [Unicode(false)]
    public string HH_MM { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? RECEITA_ESTIMADA { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string OPERADORA_CLIENTE { get; set; }

    [Unicode(false)]
    public string MOTIVO_DESCRICAO { get; set; }

    [Unicode(false)]
    public string MOTIVO_NAO_VENDA { get; set; }

    [Unicode(false)]
    public string TIPO_VENDA { get; set; }
}