// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class CNS_CONTROLE_TERCEIROS_DEMANDAS_NE
{
    [Required]
    [StringLength(70)]
    [Unicode(false)]
    public string FILA { get; set; }

    [Required]
    [StringLength(7)]
    [Unicode(false)]
    public string TIPO_CHAMADO { get; set; }

    public int ID { get; set; }

    public int MATRICULA_RESPONSAVEL { get; set; }

    [Required]
    [StringLength(33)]
    [Unicode(false)]
    public string RESPONSAVEL { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MATRICULA_SOLICITANTE { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string STATUS { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Expr1 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA_ABERTURA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_RESPOSTA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_ENCERRAMENTO { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string DESCRICAO_PROBLEMA { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string DECRICAO_SOLUCAO { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ADABAS { get; set; }

    public int QTDE { get; set; }
}