// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class CNS_RESET_SENHA
{
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Login { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Matricula { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataSolicitacao { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string Responsavel { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Ddd { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Uf { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Sistema { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string SLA { get; set; }

    [Required]
    [StringLength(9)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("Data Encerramento", TypeName = "datetime")]
    public DateTime? Data_Encerramento { get; set; }

    public int QTD { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Minutos { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string regional { get; set; }
}