// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class CNS_CONTROLE_DEMANDAS_STATUS
{
    public int ID { get; set; }

    public int ID_CHAMADO { get; set; }

    public int ID_STATUS_CHAMADO { get; set; }

    [Required]
    [Unicode(false)]
    public string STATUS { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA { get; set; }

    [Unicode(false)]
    public string MAT_QUEM_REDIRECIONOU { get; set; }
}