// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class CNS_FILA_RESPONSAVEL
{
    [Unicode(false)]
    public string MATRICULA_RESPONSAVEL { get; set; }

    public int ID_FILA_CHAMADO { get; set; }

    public int? ID { get; set; }

    [Unicode(false)]
    public string FILA { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string ADD_CAMPOS_AUTOMATICOS { get; set; }

    [Unicode(false)]
    public string MAT_QUEM_CRIOU { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string ADD_CAMPOS_MUNICIPIOS { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string TIPO_CHAMADO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string REGIONAL { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string ADD_PDV_DESTINO { get; set; }

    [Unicode(false)]
    public string LOGIN { get; set; }

    [Unicode(false)]
    public string NOME { get; set; }

    [Unicode(false)]
    public string NIVEL { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string UF { get; set; }
}