// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class CNS_BOLETA_ALTA
{
    public int IdVenda { get; set; }

    public int? DIA { get; set; }

    [Column("Data Completa Alta", TypeName = "datetime")]
    public DateTime? Data_Completa_Alta { get; set; }

    [Column("Data Alta", TypeName = "datetime")]
    public DateTime? Data_Alta { get; set; }

    [Required]
    [Column("HH:MM")]
    [StringLength(14)]
    [Unicode(false)]
    public string HH_MM { get; set; }

    [Unicode(false)]
    public string Produto { get; set; }

    [Unicode(false)]
    public string SubProduto { get; set; }

    [Unicode(false)]
    public string Plano1 { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? Valor1 { get; set; }

    [Unicode(false)]
    public string Plano2 { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? Valor2 { get; set; }

    [Unicode(false)]
    public string Plano3 { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? Valor3 { get; set; }

    public bool? Portabilidade { get; set; }

    public bool? MigracaoTecnologia { get; set; }

    public bool? OfertaConvergente { get; set; }

    public bool? ComFidelizacao { get; set; }

    [Unicode(false)]
    public string Device { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? ValorFidelizacaoDevice { get; set; }

    [Column("Plano Agrupa")]
    [Unicode(false)]
    public string Plano_Agrupa { get; set; }

    [Column("Valor Total", TypeName = "numeric(20, 2)")]
    public decimal? Valor_Total { get; set; }
}