// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("COBERTURA")]
public partial class COBERTURA
{
    public double? COD_IBGE { get; set; }

    [StringLength(255)]
    public string UF { get; set; }

    public double? DDD { get; set; }

    [StringLength(255)]
    public string Regional { get; set; }

    [StringLength(255)]
    public string Município { get; set; }

    [StringLength(255)]
    public string Móvel { get; set; }

    [Column("4G")]
    [StringLength(255)]
    public string _4G { get; set; }

    public double? Fixo { get; set; }

    [StringLength(255)]
    public string BL_Fixa { get; set; }

    [Column("Pay TV")]
    [StringLength(255)]
    public string Pay_TV { get; set; }

    [Column("Cobertura Exclusiva 3G")]
    [StringLength(255)]
    public string Cobertura_Exclusiva_3G { get; set; }
}