// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("COMISSIONAMENTO")]
public partial class COMISSIONAMENTO
{
    [StringLength(255)]
    public string uf { get; set; }

    [StringLength(255)]
    public string cod_credenc { get; set; }

    [StringLength(255)]
    public string Canal { get; set; }

    [StringLength(255)]
    public string REDE { get; set; }

    public double? cod_ent_vend { get; set; }

    public double? cod_alvo { get; set; }

    [StringLength(255)]
    public string nome_ent_abr { get; set; }

    [StringLength(255)]
    public string nome_ent { get; set; }

    [StringLength(255)]
    public string desc_tipo_comissao { get; set; }

    [StringLength(255)]
    public string Tipo { get; set; }

    [Column("Tipo 2")]
    [StringLength(255)]
    public string Tipo_2 { get; set; }

    public double? SomaDevalor { get; set; }

    [StringLength(255)]
    public string obs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? competencia { get; set; }

    [StringLength(255)]
    public string F15 { get; set; }

    [StringLength(255)]
    public string F16 { get; set; }

    [StringLength(255)]
    public string F17 { get; set; }
}