// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CONTAS_A_PAGAR_BKP")]
public partial class CONTAS_A_PAGAR_BKP
{
    [Key]
    public int Id { get; set; }

    [Unicode(false)]
    public string Adabas { get; set; }

    [Unicode(false)]
    public string Uf { get; set; }

    [Unicode(false)]
    public string Cnpj { get; set; }

    [Unicode(false)]
    public string Fornecedor { get; set; }

    [Unicode(false)]
    public string Pedido { get; set; }

    [Unicode(false)]
    public string DataDocumento { get; set; }

    [Unicode(false)]
    public string Lancamento { get; set; }

    [Unicode(false)]
    public string NotaFiscal { get; set; }

    [Unicode(false)]
    public string ValorNF { get; set; }

    [Unicode(false)]
    public string Status { get; set; }

    [Unicode(false)]
    public string Tipo { get; set; }

    [Unicode(false)]
    public string PrevisaoDataPagto { get; set; }

    [Unicode(false)]
    public string Sla { get; set; }

    [Unicode(false)]
    public string Farol { get; set; }

    [Unicode(false)]
    public string GerenteContas { get; set; }

    [Unicode(false)]
    public string Territorio { get; set; }

    [Unicode(false)]
    public string Data_Atualizacao { get; set; }
}