// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CONTROLE_DE_DEMANDAS_SUGESTOES_NOMES_CAMPOS")]
public partial class CONTROLE_DE_DEMANDAS_SUGESTOES_NOMES_CAMPO
{
    [Unicode(false)]
    public string CAMPO { get; set; }

    [Unicode(false)]
    public string MASCARA { get; set; }
}