// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVOS")]
public partial class CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVO
{
    [Key]
    public int Id { get; set; }

    public int ID_CHAMADO { get; set; }

    [Unicode(false)]
    public string NOME_CAMPO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string EXT_ARQUIVO { get; set; }

    public byte[] ARQUIVO { get; set; }

    [ForeignKey("ID_CHAMADO")]
    [InverseProperty("CONTROLE_DE_DEMANDAS_CHAMADO_ARQUIVOs")]
    public virtual CONTROLE_DE_DEMANDAS_CHAMADO ID_CHAMADONavigation { get; set; }
}