// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CONTROLE_DE_DEMANDAS_OPERADORES")]
public partial class CONTROLE_DE_DEMANDAS_OPERADORE
{
    [Required]
    [Unicode(false)]
    public string LOGIN { get; set; }

    [Required]
    [Unicode(false)]
    public string NOME { get; set; }

    [Required]
    [Unicode(false)]
    public string NIVEL { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string UF { get; set; }
}