// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CONTAS_A_PAGAR")]
public partial class CONTAS_A_PAGAR
{
    [Key]
    public int Id { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string Adabas { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Uf { get; set; }

    [Unicode(false)]
    public string Cnpj { get; set; }

    [Unicode(false)]
    public string Fornecedor { get; set; }

    [Unicode(false)]
    public string Pedido { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string DataDocumento { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string Lancamento { get; set; }

    [Unicode(false)]
    public string NotaFiscal { get; set; }

    [Column(TypeName = "decimal(20, 2)")]
    public decimal? ValorNF { get; set; }

    [Unicode(false)]
    public string Status { get; set; }

    [Unicode(false)]
    public string Tipo { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string PrevisaoDataPagto { get; set; }

    [Unicode(false)]
    public string Sla { get; set; }

    [Unicode(false)]
    public string Farol { get; set; }

    [Unicode(false)]
    public string GerenteContas { get; set; }

    [Unicode(false)]
    public string Territorio { get; set; }
}