// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CONTROLE_ACESSO_LIMITE_CREDITO")]
public partial class CONTROLE_ACESSO_LIMITE_CREDITO
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DataAcesso { get; set; }

    public int? idAcesso { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string ADABAS { get; set; }
}