// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CONTROLE_DE_DEMANDAS_CAMPO_COMBOBOX_FILA")]
public partial class CONTROLE_DE_DEMANDAS_CAMPO_COMBOBOX_FILA
{
    [Key]
    public int ID { get; set; }

    public int ID_FILA { get; set; }

    [Required]
    [Unicode(false)]
    public string CAMPO { get; set; }

    [ForeignKey("ID_FILA")]
    [InverseProperty("CONTROLE_DE_DEMANDAS_CAMPO_COMBOBOX_FILAs")]
    public virtual CONTROLE_DE_DEMANDAS_FILA ID_FILANavigation { get; set; }
}