// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CONTROLE_DEMANDAS_EVIDENCIAS")]
public partial class CONTROLE_DEMANDAS_EVIDENCIA
{
    [Key]
    public int ID { get; set; }

    public int ID_DEMANDAS { get; set; }

    public byte[] IMAGEM { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EXTENSAO { get; set; }

    [ForeignKey("ID_DEMANDAS")]
    [InverseProperty("CONTROLE_DEMANDAS_EVIDENCIAs")]
    public virtual CONTROLE_DEMANDAS_CADASTRO ID_DEMANDASNavigation { get; set; }
}