// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CONTROLE_DE_DEMANDAS_RELACAO_ITENS_CAMPO_COMBOBOX_FILA")]
public partial class CONTROLE_DE_DEMANDAS_RELACAO_ITENS_CAMPO_COMBOBOX_FILA
{
    public int ID { get; set; }

    public int ID_CAMPO_COMBOBOX_FILA { get; set; }

    [Required]
    [Unicode(false)]
    public string DESCRICAO { get; set; }

    [ForeignKey("ID_CAMPO_COMBOBOX_FILA")]
    public virtual CONTROLE_DE_DEMANDAS_CAMPO_COMBOBOX_FILA ID_CAMPO_COMBOBOX_FILANavigation { get; set; }
}