// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CONTROLE_DE_DEMANDAS_CAMPOS_CHAMADO")]
public partial class CONTROLE_DE_DEMANDAS_CAMPOS_CHAMADO
{
    [Key]
    public int ID { get; set; }

    public int ID_CHAMADO { get; set; }

    [InverseProperty("ID_CAMPOS_CHAMADONavigation")]
    public virtual ICollection<CONTROLE_DE_DEMANDAS_CHAMADO> CONTROLE_DE_DEMANDAS_CHAMADOs { get; set; } = new List<CONTROLE_DE_DEMANDAS_CHAMADO>();

    [InverseProperty("ID_CAMPOS_CHAMADONavigation")]
    public virtual ICollection<CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO> CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADOs { get; set; } = new List<CONTROLE_DE_DEMANDAS_RELACAO_CAMPOS_CHAMADO>();
}