// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CONTROLE DE DEMANDAS RELATORIO LINHA TESTE")]
public partial class CONTROLE_DE_DEMANDAS_RELATORIO_LINHA_TESTE
{
    public int? ID { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string MATRICULA_RESPONSAVEL { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string RESPONSAVEL { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string MATRICULA_SOLICITANTE { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string SOLICITANTE { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string FILA { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string CAMPO_COMBOBOX { get; set; }

    [Column("Opção Selecionada")]
    [StringLength(250)]
    [Unicode(false)]
    public string Opção_Selecionada { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string STATUS { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string MOTIVO_FECHAMENTO { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DATA_ABERTURA { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DATA_ENCERRAMENTO { get; set; }

    [Column(TypeName = "text")]
    public string DESCRICAO_PROBLEMA { get; set; }

    [Column(TypeName = "text")]
    public string DESCRICAO_SOLUCAO { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string PRIMEIRA_RESPOSTA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string REGIONAL { get; set; }
}