// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CONTROLE_DEMANDAS_CADASTRO")]
public partial class CONTROLE_DEMANDAS_CADASTRO
{
    [Key]
    public int ID { get; set; }

    public int IdAcesso { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ASSUNTO { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ADABAS { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string CPF_CLIENTE { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string LINHA_CLIENTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA_CADASTRO { get; set; }

    [Required]
    [Unicode(false)]
    public string OBSERVACOES { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CHAMADO { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string AREA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_RESOLUCAO { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string RESPONSAVEL { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string STATUS { get; set; }

    [Unicode(false)]
    public string SOLUCAO { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string CPF_COLABORADOR { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MATRICULA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LOGIN { get; set; }

    [InverseProperty("IdDemandasNavigation")]
    public virtual ICollection<CONTROLE_DEMANDAS_CHAT> CONTROLE_DEMANDAS_CHATs { get; set; } = new List<CONTROLE_DEMANDAS_CHAT>();

    [InverseProperty("ID_DEMANDASNavigation")]
    public virtual ICollection<CONTROLE_DEMANDAS_EVIDENCIA> CONTROLE_DEMANDAS_EVIDENCIAs { get; set; } = new List<CONTROLE_DEMANDAS_EVIDENCIA>();

    [ForeignKey("IdAcesso")]
    [InverseProperty("CONTROLE_DEMANDAS_CADASTROs")]
    public virtual ACESSO IdAcessoNavigation { get; set; }
}