// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CREDENCIAMENTO_RELACAO_ARQUIVOS_STATUS")]
public partial class CREDENCIAMENTO_RELACAO_ARQUIVOS_STATUS
{
    public int ID { get; set; }

    public int? ID_ARQUIVO { get; set; }

    [Required]
    [StringLength(30)]
    public string STATUS { get; set; }

    [ForeignKey("ID_ARQUIVO")]
    public virtual CREDENCIAMENTO_RELACAO_ARQUIVO ID_ARQUIVONavigation { get; set; }
}