// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("CREDENCIAMENTO_ANALISTAS_HISTORICO")]
public partial class CREDENCIAMENTO_ANALISTAS_HISTORICO
{
    [Required]
    [Unicode(false)]
    public string LOGIN { get; set; }

    public int ID_CREDENCIAMENTO { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string STATUS { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA { get; set; }

    [ForeignKey("ID_CREDENCIAMENTO")]
    public virtual CREDENCIAMENTO ID_CREDENCIAMENTONavigation { get; set; }
}