// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CREDENCIAMENTO_RELACAO_ARQUIVOS")]
public partial class CREDENCIAMENTO_RELACAO_ARQUIVO
{
    [Key]
    public int Id { get; set; }

    public int ID_CREDENCIAMENTO { get; set; }

    [Unicode(false)]
    public string NOME_CAMPO { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string EXT_ARQUIVO { get; set; }

    public byte[] ARQUIVO { get; set; }

    [ForeignKey("ID_CREDENCIAMENTO")]
    [InverseProperty("CREDENCIAMENTO_RELACAO_ARQUIVOs")]
    public virtual CREDENCIAMENTO ID_CREDENCIAMENTONavigation { get; set; }
}