// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("DASHBOARD_TERMINAIS_SIMULADOR")]
public partial class DASHBOARD_TERMINAIS_SIMULADOR
{
    [Key]
    public int Id { get; set; }

    [StringLength(350)]
    [Unicode(false)]
    public string Fornecedor { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ValorNF { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Tipo { get; set; }
}