// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("DEMANDA_CAMPOS_FILA")]
[Index("ID_SUB_FILA", Name = "IX_DEMANDA_CAMPOS_FILA_ID_SUB_FILA")]
public partial class DEMANDA_CAMPOS_FILA
{
    [Key]
    public int ID_CAMPOS { get; set; }

    public int ID_SUB_FILA { get; set; }

    [Required]
    [Unicode(false)]
    public string CAMPO { get; set; }

    [Required]
    [Unicode(false)]
    public string MASCARA { get; set; }

    public bool CAMPO_SUSPENSO { get; set; }

    [Required]
    [Unicode(false)]
    public string REGIONAL { get; set; }

    [Required]
    [Unicode(false)]
    public string DT_CRIACAO { get; set; }

    public bool STATUS_CAMPOS_FILA { get; set; }

    public int MAT_CRIADOR { get; set; }

    [InverseProperty("ID_CAMPOSNavigation")]
    public virtual ICollection<DEMANDA_VALORES_CAMPOS_SUSPENSO> DEMANDA_VALORES_CAMPOS_SUSPENSOs { get; set; } = new List<DEMANDA_VALORES_CAMPOS_SUSPENSO>();

    [ForeignKey("ID_SUB_FILA")]
    [InverseProperty("DEMANDA_CAMPOS_FILAs")]
    public virtual DEMANDA_SUB_FILA ID_SUB_FILANavigation { get; set; }
}