// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("DEMANDA_VALORES_CAMPOS_SUSPENSO")]
[Index("ID_CAMPOS", Name = "IX_DEMANDA_VALORES_CAMPOS_SUSPENSO_ID_CAMPOS")]
public partial class DEMANDA_VALORES_CAMPOS_SUSPENSO
{
    [Key]
    public int ID_VALORES { get; set; }

    [Required]
    [Unicode(false)]
    public string VALOR { get; set; }

    public int ID_CAMPOS { get; set; }

    public bool STATUS { get; set; }

    [ForeignKey("ID_CAMPOS")]
    [InverseProperty("DEMANDA_VALORES_CAMPOS_SUSPENSOs")]
    public virtual DEMANDA_CAMPOS_FILA ID_CAMPOSNavigation { get; set; }
}