// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("DEMANDA_BD_OPERADORES")]
public partial class DEMANDA_BD_OPERADORE
{
    [Key]
    public int ID { get; set; }

    public int? MATRICULA { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string REGIONAL { get; set; }

    public bool? STATUS { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_MOD { get; set; }

    public int? MATRICULA_MOD { get; set; }
}