// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("CHAMADO_HISTORICO_PRIORIDADE", Schema = "Demandas")]
public partial class CHAMADO_HISTORICO_PRIORIDADE
{
    [Key]
    public int ID { get; set; }
    public Guid ID_RELACAO { get; set; }
    [Unicode(false)]
    public int MAT_RESPONSAVEL { get; set; }
    [Unicode(false)]
    public bool PRIORIDADE { get; set; }
    [Unicode(false)]
    public DateTime DATA { get; set; }

    [ForeignKey("ID_RELACAO")]
    [JsonIgnore]
    public virtual DEMANDA_RELACAO_CHAMADO DEMANDANav { get; set; }

    [ForeignKey("MAT_RESPONSAVEL")]
    [JsonIgnore]
    public virtual ACESSOS_MOBILE? Responsavel { get; set; }
}