// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("DEMANDAS_TELEGRAM")]
public partial class DEMANDAS_TELEGRAM
{
    public double? ID { get; set; }

    public double? ID_STATUS_CHAMADO { get; set; }

    [StringLength(255)]
    public string FILA { get; set; }

    public double? MATRICULA_RESPONSAVEL { get; set; }

    [StringLength(255)]
    public string RESPONSAVEL { get; set; }

    public double? MATRICULA_SOLICITANTE { get; set; }

    [StringLength(255)]
    public string SOLICITANTE { get; set; }

    [StringLength(255)]
    public string REGIONAL { get; set; }

    [StringLength(255)]
    public string DATA_ABERTURA { get; set; }

    [StringLength(255)]
    public string DATA_FECHAMENTO { get; set; }

    [Column("MINUTOS SLA FECHAMENTOS")]
    public double? MINUTOS_SLA_FECHAMENTOS { get; set; }

    [Column("HORAS SLA FECHAMENTOS", TypeName = "datetime")]
    public DateTime? HORAS_SLA_FECHAMENTOS { get; set; }

    [StringLength(255)]
    public string STATUS { get; set; }

    [Column("DATA PRIMEIRA RESPOSTA")]
    [StringLength(255)]
    public string DATA_PRIMEIRA_RESPOSTA { get; set; }

    [Column("MINUTOS SLA PRIMEIRA RESPOSTA")]
    public double? MINUTOS_SLA_PRIMEIRA_RESPOSTA { get; set; }

    [Column("HORA PRIMEIRA RESPOSTA", TypeName = "datetime")]
    public DateTime? HORA_PRIMEIRA_RESPOSTA { get; set; }

    [StringLength(255)]
    public string MOTIVO_FECHAMENTO_SUPORTE { get; set; }

    [StringLength(255)]
    public string AREA { get; set; }

    [StringLength(255)]
    public string TIPO_CHAMADO { get; set; }
}