// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("DEMANDAS_JSON")]
public partial class DEMANDAS_JSON
{
    public int ID { get; set; }

    public int ID_FILA { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string REPOSTA { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string STATUS { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string REGIONAL { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string DADOS_ABERTURA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA_CADASTRO { get; set; }

    [Required]
    [Unicode(false)]
    public string OBSERVACOES { get; set; }
}