// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("DEMANDA_TIPO_FILA")]
public partial class DEMANDA_TIPO_FILA
{
    [Key]
    public int ID_TIPO_FILA { get; set; }

    [Required]
    [Unicode(false)]
    public string NOME_TIPO_FILA { get; set; }

    [Required]
    [Unicode(false)]
    public string REGIONAL { get; set; }

    public bool STATUS_TIPO_FILA { get; set; }

    public int MAT_CRIADOR { get; set; }

    [Required]
    [Unicode(false)]
    public string DT_CRIACAO { get; set; }

    [Unicode(false)]
    public string DESCRICAO { get; set; }

    [InverseProperty("ID_TIPO_FILANavigation")]
    public virtual ICollection<DEMANDA_SUB_FILA> DEMANDA_SUB_FILAs { get; set; } = new List<DEMANDA_SUB_FILA>();
}