// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("DESCREDENCIAMENTO_COMPLETO_DADOS_BKP")]
public partial class DESCREDENCIAMENTO_COMPLETO_DADOS_BKP
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ADABAS { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string STATUS_DESCREDENCIAMENTO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_INFORMADA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_DATA_INFORMADA { get; set; }

    [Column(TypeName = "text")]
    public string OBSERVACAO { get; set; }

    public int? IdAcesso { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string LISTA { get; set; }

    [Column("SLA LINHA")]
    public int? SLA_LINHA { get; set; }
}