// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("DESCREDENCIAMENTO_CADASTRO")]
public partial class DESCREDENCIAMENTO_CADASTRO
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(225)]
    [Unicode(false)]
    public string ADABAS { get; set; }

    [Required]
    [StringLength(225)]
    [Unicode(false)]
    public string TIPO_DESCREDENCIAMENTO { get; set; }

    [Unicode(false)]
    public string MOTIVO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA_CADASTRO { get; set; }

    public byte[] ARQUIVO_DESCREDENCIAMENTO { get; set; }

    public int IDACESSO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EXTENSAO_ARQUIVO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TIPO_ARQUIVO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string STATUS { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string CANCELADO { get; set; }

    [InverseProperty("ID_DESCREDENCIAMENTONavigation")]
    public virtual ICollection<DESCREDENCIAMENTO_AMIGAVEL_OLD> DESCREDENCIAMENTO_AMIGAVEL_OLDs { get; set; } = new List<DESCREDENCIAMENTO_AMIGAVEL_OLD>();

    [InverseProperty("ID_DESCREDENCIAMENTO_CADASTRONavigation")]
    public virtual ICollection<DESCREDENCIAMENTO_COMPLETO_DADOS_TESTE> DESCREDENCIAMENTO_COMPLETO_DADOS_TESTEs { get; set; } = new List<DESCREDENCIAMENTO_COMPLETO_DADOS_TESTE>();

    [InverseProperty("ID_DESCREDENCIAMENTO_CADASTRONavigation")]
    public virtual ICollection<DESCREDENCIAMENTO_COMPLETO_DADO> DESCREDENCIAMENTO_COMPLETO_DADOs { get; set; } = new List<DESCREDENCIAMENTO_COMPLETO_DADO>();

    [InverseProperty("ID_DESCREDENCIAMENTONavigation")]
    public virtual ICollection<DESCREDENCIAMENTO_DENUNCIA_IMOTIVADA_OLD> DESCREDENCIAMENTO_DENUNCIA_IMOTIVADA_OLDs { get; set; } = new List<DESCREDENCIAMENTO_DENUNCIA_IMOTIVADA_OLD>();

    [InverseProperty("ID_DESCREDENCIAMENTONavigation")]
    public virtual ICollection<DESCREDENCIAMENTO_INATIVIDADE_OLD> DESCREDENCIAMENTO_INATIVIDADE_OLDs { get; set; } = new List<DESCREDENCIAMENTO_INATIVIDADE_OLD>();

    [InverseProperty("ID_DESCREDENCIAMENTONavigation")]
    public virtual ICollection<DESCREDENCIAMENTO_VIGENCIA_CONTRATO_OLD> DESCREDENCIAMENTO_VIGENCIA_CONTRATO_OLDs { get; set; } = new List<DESCREDENCIAMENTO_VIGENCIA_CONTRATO_OLD>();

    [ForeignKey("IDACESSO")]
    [InverseProperty("DESCREDENCIAMENTO_CADASTROs")]
    public virtual ACESSO IDACESSONavigation { get; set; }
}