// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("ESTOQUE_VITRINE_VIRTUAL")]
public partial class ESTOQUE_VITRINE_VIRTUAL
{
    [StringLength(255)]
    public string CENTRO { get; set; }

    [StringLength(255)]
    public string MATERIAL { get; set; }

    [Unicode(false)]
    public string DESCRICAO { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string DEPOSITO { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string SALDO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_CARGA { get; set; }
}