// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("FAT_MANUAL_STATUS")]
public partial class FAT_MANUAL_STATUS
{
    [Key]
    public int ID { get; set; }

    public int? ID_FATURAMENTO { get; set; }

    [Required]
    [Unicode(false)]
    public string RESPOSTA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA { get; set; }

    public int MATRICULA { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string STATUS { get; set; }

    [ForeignKey("ID_FATURAMENTO")]
    [InverseProperty("FAT_MANUAL_STATUSes")]
    public virtual QUALIDADE_BD_MANUAL_AUDIT ID_FATURAMENTONavigation { get; set; }
}