// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("FATURAMENTOSAP")]
public partial class FATURAMENTOSAP
{
    [Column(TypeName = "datetime")]
    public DateTime? MES { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_MVMT_LNHA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_NF { get; set; }

    [StringLength(255)]
    public string NR_NOTA_FSCL { get; set; }

    [StringLength(255)]
    public string NR_SRAL { get; set; }

    [StringLength(255)]
    public string CD_DOCT_FTRM { get; set; }

    [StringLength(255)]
    public string CD_ORDM_VNDA { get; set; }

    [StringLength(255)]
    public string CD_TIPO_ORDM_VNDA { get; set; }

    [StringLength(255)]
    public string NM_TIPO_ORDM_VNDA { get; set; }

    [StringLength(255)]
    public string NR_CPF_CNPJ_SAP { get; set; }

    [StringLength(255)]
    public string CPF_CLIENTE { get; set; }

    [StringLength(255)]
    public string NM_RZAO_SCAL { get; set; }

    [StringLength(255)]
    public string ORGV { get; set; }

    [StringLength(255)]
    public string UF { get; set; }

    [StringLength(255)]
    public string REGIONAL { get; set; }

    [StringLength(255)]
    public string TERRITORIO { get; set; }

    [StringLength(255)]
    public string TERRITORIO_UF { get; set; }

    public double? DDD { get; set; }

    [StringLength(255)]
    public string SEGMENTO { get; set; }

    [StringLength(255)]
    public string TIPO_CLT { get; set; }

    [StringLength(255)]
    public string CD { get; set; }

    [StringLength(255)]
    public string CANAL_FATURAMENTO { get; set; }

    [StringLength(255)]
    public string CENT { get; set; }

    [StringLength(255)]
    public string NOME_FANTASIA { get; set; }

    [StringLength(255)]
    public string REDE { get; set; }

    [StringLength(255)]
    public string CNPJ_PDV { get; set; }

    [StringLength(255)]
    public string CEP_PDV { get; set; }

    [StringLength(255)]
    public string ATIVIDADE { get; set; }

    [StringLength(255)]
    public string GENERO { get; set; }

    [StringLength(255)]
    public string ATVD_CNL { get; set; }

    public double? FG_SHOPPING { get; set; }

    public double? FG_QUIOSQUE { get; set; }

    public double? FG_ESTOQUE_ZERO { get; set; }

    [StringLength(255)]
    public string CLASS_CLUSTER { get; set; }

    [StringLength(255)]
    public string CLASS_DEALER { get; set; }

    [StringLength(255)]
    public string VOUCHER { get; set; }

    [StringLength(255)]
    public string CD_MTRL { get; set; }

    [StringLength(255)]
    public string ID_DPGC { get; set; }

    [StringLength(255)]
    public string CLASSIF_CATEGORIA { get; set; }

    [StringLength(255)]
    public string CATEGORIA { get; set; }

    [StringLength(255)]
    public string MODELO { get; set; }

    [StringLength(255)]
    public string NOME_COMERCIAL { get; set; }

    [StringLength(255)]
    public string FABRICANTE { get; set; }

    [StringLength(255)]
    public string GAMA { get; set; }

    [StringLength(255)]
    public string TECNOLOGIA_APARELHO { get; set; }

    [StringLength(255)]
    public string SISTEMA_OPERACIONAL { get; set; }

    [StringLength(255)]
    public string CD_COND_PGTO { get; set; }

    [StringLength(255)]
    public string NM_COND_PGTO { get; set; }

    [StringLength(255)]
    public string DEPOSITO { get; set; }

    [StringLength(255)]
    public string NM_DPST { get; set; }

    public double? QTDE_FATURADA { get; set; }

    public double? VALOR_NF { get; set; }

    public double? RECEITA_BRUTA { get; set; }

    public double? DESCONTO_TOTAL { get; set; }

    public double? VL_ICMS { get; set; }

    public double? ICMS_ST_BLENDED { get; set; }

    public double? PIS { get; set; }

    public double? COFINS { get; set; }

    public double? RECEITA_LIQUIDA_S_PRICE { get; set; }

    public double? RECEITA_LIQUIDA { get; set; }

    public double? CMV { get; set; }

    public double? VL_MARGEM_BRUTA { get; set; }

    public double? REBATE { get; set; }

    public double? VL_PRICE_FCDI { get; set; }

    public double? VALOR_DESCONTO_PPTO { get; set; }

    public double? VALOR_PAGO_PROG_PNTO { get; set; }

    public double? DESCONTO_FABRICANTE { get; set; }

    public double? DESCONTO_RENOVA { get; set; }

    public double? VL_SUBSIDIO_CALCULADO { get; set; }

    public double? VALOR_VENDA { get; set; }

    public double? VL_PVP_DW { get; set; }

    public double? VL_VNDA_VGO { get; set; }

    public double? DESCONTO_MANUAL { get; set; }

    [StringLength(255)]
    public string MODELO_RECEBIDO { get; set; }

    public double? ID_CLASSIF_PED { get; set; }

    [StringLength(255)]
    public string DESC_CLASSIF_PED { get; set; }

    public double? ID_CLASSIF_DOA { get; set; }

    [StringLength(255)]
    public string DESC_CLASSIF_DOA { get; set; }

    public double? FLAG_PROG_PNTO { get; set; }

    [StringLength(255)]
    public string FLAG_DESCONTO_MANUAL { get; set; }

    public double? FLAG_ONLINE_LLPP { get; set; }

    [StringLength(255)]
    public string FLAG_RENOVA { get; set; }

    public double? FLAG_ATIVADO { get; set; }

    public double? FLAG_ULTIMO_FAT { get; set; }

    public double? FLAG_MOVIMENTO { get; set; }

    public double? FLAG_FONTE { get; set; }

    [StringLength(255)]
    public string DESC_FLAG_FONTE { get; set; }

    public double? FLAG_PORTABILIDADE { get; set; }

    [StringLength(255)]
    public string CD_TIPO_PDDO { get; set; }

    [StringLength(255)]
    public string NM_TIPO_PDDO { get; set; }

    public double? ID_TIPO_MVMT_LNHA { get; set; }

    [StringLength(255)]
    public string DS_TIPO_MVMT_LNHA { get; set; }

    [StringLength(255)]
    public string AGRP_MVMT_LNHA { get; set; }

    [StringLength(255)]
    public string AREA_REGISTRO { get; set; }

    public double? NR_TLFN { get; set; }

    [StringLength(255)]
    public string DS_PLTF { get; set; }

    [StringLength(255)]
    public string DS_SIST_PGTO { get; set; }

    [StringLength(255)]
    public string SEGMENTO_PLANO { get; set; }

    [StringLength(255)]
    public string CD_PLNO_SIST_ORIG { get; set; }

    [StringLength(255)]
    public string DS_PLNO { get; set; }

    [StringLength(255)]
    public string PLANO_PRICING { get; set; }

    [StringLength(255)]
    public string TIT_DEP { get; set; }

    [StringLength(255)]
    public string CD_CRDN { get; set; }

    [StringLength(255)]
    public string NM_LOGN_ATND { get; set; }

    [StringLength(255)]
    public string FLAG_FDLZ { get; set; }

    [StringLength(255)]
    public string SCORE { get; set; }

    [StringLength(255)]
    public string FLAG_POLITICA_SCORE { get; set; }

    [StringLength(255)]
    public string SEMANA_DO_ANO { get; set; }

    [StringLength(255)]
    public string SEMANA_DO_MÊS { get; set; }

    [StringLength(255)]
    public string CLASSIF_DIFERIMENTO { get; set; }

    [StringLength(255)]
    public string FLAG_VENHA_SER_VIVO { get; set; }

    [StringLength(255)]
    public string DESC_CAMP { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_REF_PAGAMENTO { get; set; }

    [StringLength(255)]
    public string FLAG_FCDI { get; set; }

    [StringLength(255)]
    public string NM_LOGN_ATND_SAP { get; set; }

    [StringLength(255)]
    public string NM_LOGN_ATND_FDLZ { get; set; }

    public double? FLAG_PICK_UP_IN_STORE { get; set; }

    [StringLength(255)]
    public string NM_SIST_ORIG { get; set; }

    [StringLength(255)]
    public string MOT_ORDEM { get; set; }

    public double? FLAG_ONLINE_RVNDA { get; set; }

    [StringLength(255)]
    public string DS_TIPO_MVMT_UP_DOWN { get; set; }

    public double? FLAG_VITRINE { get; set; }

    [StringLength(255)]
    public string SG_TRRT_PDV { get; set; }

    [StringLength(255)]
    public string NO_TRRT_PDV { get; set; }
}