// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("HEADCOUNT")]
public partial class HEADCOUNT
{
    public double? Ano { get; set; }

    public double? Mês { get; set; }

    public double? Matrícula { get; set; }

    [StringLength(255)]
    public string Nome { get; set; }

    [StringLength(255)]
    public string UF { get; set; }

    [StringLength(255)]
    public string Regional { get; set; }

    [StringLength(255)]
    public string Empresa { get; set; }

    [Column("Área RH")]
    [StringLength(255)]
    public string Área_RH { get; set; }

    [StringLength(255)]
    public string Subarea { get; set; }

    [StringLength(255)]
    public string Filial { get; set; }

    public double? Unidade { get; set; }

    [StringLength(255)]
    public string Sigla { get; set; }

    [StringLength(255)]
    public string VP { get; set; }

    [Column("Dir 1")]
    [StringLength(255)]
    public string Dir_1 { get; set; }

    [Column("Dir 2")]
    [StringLength(255)]
    public string Dir_2 { get; set; }

    [Column("Div ")]
    [StringLength(255)]
    public string Div_ { get; set; }

    [StringLength(255)]
    public string Ger { get; set; }

    [StringLength(255)]
    public string Área { get; set; }

    [Column("Mat Gestor")]
    public double? Mat_Gestor { get; set; }

    [StringLength(255)]
    public string Gestor { get; set; }

    [Column("Centro Custo")]
    [StringLength(255)]
    public string Centro_Custo { get; set; }

    [Column("Objeto Custo")]
    [StringLength(255)]
    public string Objeto_Custo { get; set; }

    [Column("Ordem Interna")]
    [StringLength(255)]
    public string Ordem_Interna { get; set; }

    [Column("Cod Cargo")]
    public double? Cod_Cargo { get; set; }

    [StringLength(255)]
    public string Cargo { get; set; }

    [Column("Nv Rel Espanha")]
    [StringLength(255)]
    public string Nv_Rel_Espanha { get; set; }

    [StringLength(255)]
    public string Grupo { get; set; }

    [StringLength(255)]
    public string Subgrupo { get; set; }

    [StringLength(255)]
    public string Vinculo { get; set; }

    [Column("Posição SAP HCM")]
    public double? Posição_SAP_HCM { get; set; }

    [Column("Posição SSFF")]
    [StringLength(255)]
    public string Posição_SSFF { get; set; }

    [StringLength(255)]
    public string Pirâmide { get; set; }

    [StringLength(255)]
    public string Executivo { get; set; }

    [StringLength(255)]
    public string Nível { get; set; }

    [StringLength(255)]
    public string Loja { get; set; }

    [Column("Call Center ")]
    [StringLength(255)]
    public string Call_Center_ { get; set; }

    [Column("Variável Vendas")]
    [StringLength(255)]
    public string Variável_Vendas { get; set; }

    [Column("Data Admissão", TypeName = "datetime")]
    public DateTime? Data_Admissão { get; set; }

    [Column("Tempo Empresa")]
    public double? Tempo_Empresa { get; set; }

    [Column("Tipo Ponto")]
    [StringLength(255)]
    public string Tipo_Ponto { get; set; }

    [StringLength(255)]
    public string Teletrabalho { get; set; }

    [Column("Âmbito Organizacional")]
    [StringLength(255)]
    public string Âmbito_Organizacional { get; set; }

    [Column("Emp Hyperion")]
    [StringLength(255)]
    public string Emp_Hyperion { get; set; }

    [Column("Área Funcional Hyperion")]
    [StringLength(255)]
    public string Área_Funcional_Hyperion { get; set; }

    [Column("Data Nascimento", TypeName = "datetime")]
    public DateTime? Data_Nascimento { get; set; }

    public double? Idade { get; set; }

    [Column("Cont-Idade")]
    [StringLength(255)]
    public string Cont_Idade { get; set; }

    [StringLength(255)]
    public string Sexo { get; set; }

    [Column("Estado Civil")]
    [StringLength(255)]
    public string Estado_Civil { get; set; }

    [StringLength(255)]
    public string Raça { get; set; }

    [Column("Grau de Instrução")]
    [StringLength(255)]
    public string Grau_de_Instrução { get; set; }

    [StringLength(255)]
    public string Formação { get; set; }

    [StringLength(255)]
    public string CPF { get; set; }

    [StringLength(255)]
    public string RG { get; set; }

    [StringLength(255)]
    public string Nacionalidade { get; set; }

    [StringLength(255)]
    public string PCD { get; set; }

    [Column("Email ")]
    [StringLength(255)]
    public string Email_ { get; set; }

    [StringLength(255)]
    public string Celular { get; set; }

    [StringLength(255)]
    public string Comercial { get; set; }

    [StringLength(255)]
    public string Afastado { get; set; }

    [StringLength(255)]
    public string Motivo { get; set; }

    [StringLength(255)]
    public string Início { get; set; }

    [StringLength(255)]
    public string Término { get; set; }

    [Column("Tempo Afastamento")]
    [StringLength(255)]
    public string Tempo_Afastamento { get; set; }

    [StringLength(255)]
    public string Estável { get; set; }

    [StringLength(255)]
    public string Estabilidade { get; set; }

    [StringLength(255)]
    public string Início1 { get; set; }

    [StringLength(255)]
    public string Término1 { get; set; }

    [Column("Headcount")]
    public double? Headcount1 { get; set; }

    [Column("Férias no Mês")]
    [StringLength(255)]
    public string Férias_no_Mês { get; set; }

    [Column("Início Férias")]
    [StringLength(255)]
    public string Início_Férias { get; set; }

    [Column("Término Férias")]
    [StringLength(255)]
    public string Término_Férias { get; set; }

    [Column("Nº Dep IRRF")]
    [StringLength(255)]
    public string Nº_Dep_IRRF { get; set; }

    public double? FTE { get; set; }

    [Column("Operação Global")]
    [StringLength(255)]
    public string Operação_Global { get; set; }

    [StringLength(255)]
    public string CelClub { get; set; }

    [StringLength(255)]
    public string Sindicalizado { get; set; }

    [Column("Prev Privada ")]
    [StringLength(255)]
    public string Prev_Privada_ { get; set; }

    [StringLength(255)]
    public string Plano { get; set; }

    [Column("Assist Médica")]
    [StringLength(255)]
    public string Assist_Médica { get; set; }

    [StringLength(255)]
    public string Plano1 { get; set; }

    [Column("Tipo de Plano")]
    [StringLength(255)]
    public string Tipo_de_Plano { get; set; }

    [Column("Endereço - Infotipo  - 6")]
    [StringLength(255)]
    public string Endereço___Infotipo____6 { get; set; }

    public double? Número { get; set; }

    public double? Comp { get; set; }

    [StringLength(255)]
    public string Bairro { get; set; }

    [StringLength(255)]
    public string Cidade { get; set; }

    [StringLength(255)]
    public string UF1 { get; set; }

    [StringLength(255)]
    public string CEP { get; set; }

    [StringLength(255)]
    public string CNPJ { get; set; }

    [Column("Endereço Comercial")]
    [StringLength(255)]
    public string Endereço_Comercial { get; set; }

    [StringLength(255)]
    public string Número1 { get; set; }

    [StringLength(255)]
    public string Comp1 { get; set; }

    [StringLength(255)]
    public string Bairro1 { get; set; }

    [StringLength(255)]
    public string Cidade1 { get; set; }

    [StringLength(255)]
    public string UF2 { get; set; }

    [StringLength(255)]
    public string CEP1 { get; set; }

    [StringLength(255)]
    public string Processo { get; set; }
}