// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("HISTORICO_BOLETA_BD_PALITAGEM")]
public partial class HISTORICO_BOLETA_BD_PALITAGEM
{
    [Key]
    public int ID_HISTORICO_BOLETA { get; set; }

    public int ID_BOLETA { get; set; }

    public int MATRICULA { get; set; }

    [Unicode(false)]
    public string RESPOSTA { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string STATUS { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA { get; set; }

    [ForeignKey("ID_BOLETA")]
    [InverseProperty("HISTORICO_BOLETA_BD_PALITAGEMs")]
    public virtual BOLETA_BD_PALITAGEM ID_BOLETANavigation { get; set; }
}