// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("ITENS_NAO_VENDA")]
public partial class ITENS_NAO_VENDum
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string INDICADOR { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MOTIVO { get; set; }
}