// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("JORNADA_BD_QUESTION")]
public partial class JORNADA_BD_QUESTION
{
    [Key]
    public int ID_QUESTION { get; set; }

    public int? ID_TEMAS { get; set; }

    [StringLength(255)]
    public string TP_FORMS { get; set; }

    [StringLength(255)]
    public string TP_QUESTAO { get; set; }

    [Unicode(false)]
    public string PERGUNTA { get; set; }

    [Unicode(false)]
    public string REGIONAL { get; set; }

    public double? PESO { get; set; }

    public string EXPLICACAO { get; set; }

    [StringLength(255)]
    public string CANAL { get; set; }

    [StringLength(255)]
    public string CARGO { get; set; }

    public IEnumerable<int> listCargos() => CARGO.Split(new[] { ';' }).Select(c => int.Parse(c));

    public bool? STATUS_QUESTION { get; set; }

    public bool? FIXA { get; set; }

    public int? ID_SUB_TEMAS { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_MOD { get; set; }

    public int? LOGIN_MOD { get; set; }
}