// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("JORNADA_BD_ANSWER_AVALIACAO")]
public partial class JORNADA_BD_ANSWER_AVALIACAO
{
    [Key]
    public int ID_PROVA_RESPONDIDA { get; set; }

    [Unicode(false)]
    public string ID_TEMAS { get; set; }

    [StringLength(255)]
    public string TP_FORMS { get; set; }

    public int? PUBLICO_CANAL { get; set; }

    public int? PUBLICO_CARGO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_AVALIACAO { get; set; }

    public int? MATRICULA_APLICADOR { get; set; }

    [StringLength(255)]
    public string NOME_APLICADOR { get; set; }

    public int? CADERNO { get; set; }

    [Column(TypeName = "decimal(4, 1)")]
    public decimal? NOTA { get; set; }

    [Unicode(false)]
    public string REDE_AVALIADA { get; set; }

    public int? DDD_AVALIADO { get; set; }

    [Unicode(false)]
    public string PDV_AVALIADO { get; set; }

    public int? RE_AVALIADO { get; set; }

    [Unicode(false)]
    public string ID_SUB_TEMAS { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string REGIONAL { get; set; }

    public int? ID_PROVA { get; set; }
}