// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class JORNADA_BD_CARTEIRA_DIVISAO
{
    public double? DIVISAO { get; set; }

    [StringLength(255)]
    public string NOME_DIVISAO { get; set; }

    [StringLength(255)]
    public string RE_GA { get; set; }

    [Column("GA / GG")]
    [StringLength(255)]
    public string GA___GG { get; set; }

    [StringLength(255)]
    public string RE_GGP { get; set; }

    [StringLength(255)]
    public string GGP { get; set; }

    [StringLength(255)]
    public string RE_GV { get; set; }

    [StringLength(255)]
    public string GV { get; set; }

    public double? DDD_LOCALIDADE_PDV { get; set; }

    [StringLength(255)]
    public string Uf { get; set; }

    [StringLength(255)]
    public string Cnpj { get; set; }

    [StringLength(255)]
    public string Vendedor { get; set; }
}