// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("JORNADA_BD_TEMAS_SUB_TEMAS")]
public partial class JORNADA_BD_TEMAS_SUB_TEMA
{
    [Key]
    public int ID_SUB_TEMAS { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string SUB_TEMAS { get; set; }

    public int? ID_TEMAS { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string TEMAS { get; set; }
}