// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("JORNADA_BD_ANSWER_ALTERNATIVAS")]
public partial class JORNADA_BD_ANSWER_ALTERNATIVA
{
    [Key]
    public int ID_ALTERNATIVA { get; set; }

    public string ALTERNATIVA { get; set; }

    public int? ID_QUESTION { get; set; }

    public bool? STATUS_ALTERNATIVA { get; set; }

    public double? PESO { get; set; }

    public bool? RESPOSTA_CORRETA { get; set; }
}