// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("JUSTIFICATIVA_HE")]
public partial class JUSTIFICATIVA_HE
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(8)]
    [Unicode(false)]
    public string MATRICULA { get; set; }

    [Required]
    [StringLength(1000)]
    [Unicode(false)]
    public string JUSTIFICATIVA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string AREA { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string NOME { get; set; }

    public TimeSpan? HORAS_EXCEDIDAS { get; set; }
}