// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("LOGRADOUROS")]
public partial class LOGRADOURO
{
    public int num_cep { get; set; }

    public int bairro_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string desc_logradouro { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string desc_tipo { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string numero { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ard_metalica { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string tbox_metalica { get; set; }

    public int? pares_metalica { get; set; }

    public int? pares_ocupados_metalica { get; set; }

    public int? pares_disponiveis_metalica { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string lote_cobertura_fibra { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ard_fibra { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string cx_fibra { get; set; }

    public int? ra_fibra { get; set; }

    public int? rb_fibra { get; set; }

    public int? rc_fibra { get; set; }

    public int? na_fibra { get; set; }

    public int? nb_fibra { get; set; }

    public int? nc_fibra { get; set; }

    public int? capacidade_caixa_fibra { get; set; }

    public int? disponibilidade_caixa_fibra { get; set; }
}