// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("LOJA_CONTESTACAO_FATURA")]
public partial class LOJA_CONTESTACAO_FATURA
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string Loja { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string Linha { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string CPF { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string MesReferencia { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string Conta { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string Produto { get; set; }

    [Unicode(false)]
    public string OBS { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Valor { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoContestacao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataCadastro { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Motivo { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Ddd { get; set; }

    public int IdAcesso { get; set; }

    [ForeignKey("IdAcesso")]
    [InverseProperty("LOJA_CONTESTACAO_FATURAs")]
    public virtual ACESSO IdAcessoNavigation { get; set; }
}