// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("LOJAS_GERACAO_CARGAS_BKP")]
public partial class LOJAS_GERACAO_CARGAS_BKP
{
    [StringLength(255)]
    [Unicode(false)]
    public string PDV { get; set; }

    [Column("TIPO LOJAS")]
    [StringLength(255)]
    [Unicode(false)]
    public string TIPO_LOJAS { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string CNPJ { get; set; }

    [Column("LOGIN SIEBEL")]
    [StringLength(255)]
    [Unicode(false)]
    public string LOGIN_SIEBEL { get; set; }

    [Column("SCA - VIVO360")]
    [StringLength(255)]
    [Unicode(false)]
    public string SCA___VIVO360 { get; set; }

    [Column("VIVO NEXT")]
    [StringLength(255)]
    [Unicode(false)]
    public string VIVO_NEXT { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string GSS { get; set; }

    [Column("COD GSS")]
    [StringLength(255)]
    [Unicode(false)]
    public string COD_GSS { get; set; }

    [Column("POOL DE COBRANÇA")]
    [StringLength(255)]
    [Unicode(false)]
    public string POOL_DE_COBRANÇA { get; set; }

    [Column("GLOBAL ONE")]
    [StringLength(255)]
    [Unicode(false)]
    public string GLOBAL_ONE { get; set; }

    [Column("RAZÃO SOCIAL")]
    [StringLength(255)]
    [Unicode(false)]
    public string RAZÃO_SOCIAL { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string CIDADE { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string UF { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string DDD { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string TELEFONE { get; set; }

    [Column("E-MAIL")]
    [StringLength(255)]
    [Unicode(false)]
    public string E_MAIL { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string REDE { get; set; }

    [Column("GERENTE CONTAS")]
    [StringLength(255)]
    [Unicode(false)]
    public string GERENTE_CONTAS { get; set; }

    [Column("SELL IN")]
    [StringLength(255)]
    [Unicode(false)]
    public string SELL_IN { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string SEÇÃO { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string DIVISÃO { get; set; }

    [Column("AREA SEÇÃO")]
    [StringLength(255)]
    [Unicode(false)]
    public string AREA_SEÇÃO { get; set; }

    [Column("UNIDADE SEÇÃO")]
    public double? UNIDADE_SEÇÃO { get; set; }

    [Column("AREA DIVISÃO")]
    [StringLength(255)]
    [Unicode(false)]
    public string AREA_DIVISÃO { get; set; }

    [Column("UNIDADE DIVISÃO")]
    public double? UNIDADE_DIVISÃO { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string StatusCallidus { get; set; }
}