// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("MATRIZ_ACESSO_CONCESSAO")]
public partial class MATRIZ_ACESSO_CONCESSAO
{
    [StringLength(150)]
    [Unicode(false)]
    public string Cargo { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Canal { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string Matricula { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string DataAdmissao { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Uf { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Area { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string AreaProposta { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string SistemaUtilizado { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Perfil { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Login { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Senha { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DataAlteracao { get; set; }
}