// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("MOVIMENTACOES_BKP")]
public partial class MOVIMENTACOES_BKP
{
    [StringLength(255)]
    public string STATUS { get; set; }

    [StringLength(255)]
    public string TIPO_MOVIMENTO { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MATRICULA { get; set; }

    [StringLength(255)]
    public string NOME { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DATA_ADMISSAO { get; set; }

    [StringLength(255)]
    public string UF_PROPOSTA { get; set; }

    [StringLength(255)]
    public string CARGO_PROPOSTA { get; set; }

    [StringLength(255)]
    public string SIGLA_PROPOSTA { get; set; }

    [StringLength(255)]
    public string VP_PROPOSTA { get; set; }

    [StringLength(255)]
    public string AREA { get; set; }

    [StringLength(255)]
    public string AREA_PROPOSTA { get; set; }

    [StringLength(255)]
    public string DATA_ALTERACAO { get; set; }
}