// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("OCORRENCIAS_SISTEMICAS_REDE")]
public partial class OCORRENCIAS_SISTEMICAS_REDE
{
    [Key]
    public int ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Data { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Uf { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string DDD { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [Unicode(false)]
    public string GC { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string Canal { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string HoraInicio { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string HoraFim { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Duracao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataFinal { get; set; }

    [Unicode(false)]
    public string Motivo { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string Status { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Plantonista { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_INICIO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string HORA_INICIO { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string NR_INCIDENTE { get; set; }
}