// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("PALITAGEM_LLPP")]
public partial class PALITAGEM_LLPP
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PROTOCOLO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CPF { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string PLANO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LINHA { get; set; }

    [Column("TIPO MOVIMENTO")]
    [StringLength(50)]
    [Unicode(false)]
    public string TIPO_MOVIMENTO { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MOVIMENTO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MATRICULA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATA_CADASTRO { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string PRESENTINHO { get; set; }

    [StringLength(350)]
    [Unicode(false)]
    public string LOJA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SISTEMA { get; set; }

    [StringLength(750)]
    [Unicode(false)]
    public string PLANOATUAL { get; set; }

    [StringLength(750)]
    [Unicode(false)]
    public string PLANOANTERIOR { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string DEVICE { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string IMEI { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string LINHA_TEMPORARIO { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string LINHA_MIGRADA { get; set; }
}