// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("PERFIL_GERACAO_CARGAS")]
public partial class PERFIL_GERACAO_CARGA
{
    [Unicode(false)]
    public string PERFIL { get; set; }

    [Column("Vivo 360 Loja")]
    [Unicode(false)]
    public string Vivo_360_Loja { get; set; }

    [Column("Vivo Next")]
    [Unicode(false)]
    public string Vivo_Next { get; set; }

    [Unicode(false)]
    public string GEDOC { get; set; }

    [Column("Siebel 15")]
    [Unicode(false)]
    public string Siebel_15 { get; set; }

    [Column("E-SIM")]
    [Unicode(false)]
    public string E_SIM { get; set; }

    [Column("LOJA ONLINE")]
    [Unicode(false)]
    public string LOJA_ONLINE { get; set; }

    [Unicode(false)]
    public string REDEEXT { get; set; }

    [Unicode(false)]
    public string VIVONET { get; set; }

    [Column("VIS FAT")]
    [Unicode(false)]
    public string VIS_FAT { get; set; }

    [Column("GRP SEG")]
    [Unicode(false)]
    public string GRP_SEG { get; set; }

    [Column("GRP SEG2")]
    [Unicode(false)]
    public string GRP_SEG2 { get; set; }

    [Column("GRP SEG3")]
    [Unicode(false)]
    public string GRP_SEG3 { get; set; }

    [Column("GRP SEG4")]
    [Unicode(false)]
    public string GRP_SEG4 { get; set; }

    [Unicode(false)]
    public string PLATON { get; set; }

    [Column("VIVO CRÉDITO")]
    [Unicode(false)]
    public string VIVO_CRÉDITO { get; set; }

    [Unicode(false)]
    public string ATLYS { get; set; }

    [Unicode(false)]
    public string NGINCARE { get; set; }

    [Unicode(false)]
    public string GPS { get; set; }

    [Unicode(false)]
    public string GSS { get; set; }

    [Unicode(false)]
    public string TOKEN { get; set; }

    [Column("PAP MOBILE")]
    [Unicode(false)]
    public string PAP_MOBILE { get; set; }

    [Column("GLOBAL ONE")]
    [Unicode(false)]
    public string GLOBAL_ONE { get; set; }

    [Unicode(false)]
    public string SPN { get; set; }

    [Unicode(false)]
    public string SICS { get; set; }

    [Unicode(false)]
    public string GSS2 { get; set; }

    [Unicode(false)]
    public string PSI { get; set; }

    [Unicode(false)]
    public string ADIANTE { get; set; }
}