// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("PERFIL_USUARIO")]
public partial class PERFIL_USUARIO
{
    [Key]
    public int ID { get; set; }

    public int? MATRICULA { get; set; }

    public int? id_Perfil { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_MOD { get; set; }

    public int? LOGIN_MOD { get; set; }
}