// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("PERFIL_USUARIO_PENDENTE")]
public partial class PERFIL_USUARIO_PENDENTE
{
    [Key]
    public int ID { get; set; }

    public int? ID_ACESSO_PENDENTE { get; set; }

    public int? ID_PERFIL { get; set; }
}