// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("PERFIL_PLATAFORMAS_VIVO")]
public partial class PERFIL_PLATAFORMAS_VIVO
{
    [Key]
    public int ID_PERFIL { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Perfil { get; set; }

    [Unicode(false)]
    public string obs { get; set; }

    [Unicode(false)]
    public string CARGO { get; set; }
}