// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("PRE_PEX_EXTERNO")]
public partial class PRE_PEX_EXTERNO
{
    public int Id { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Uf { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Ddd { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string Adabas { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Cnpj { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Bairro { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string CurvaPDV { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string RecargaEletronicaFuncionando { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PDVTrabalhaComChip { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string ConsultaSerial { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PositivacaoMaterialMerchanInterno { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PossuiMaterialInternoVisivel { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PossuiMaterialMerchanInternoConcorrencia { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PositivacaoMaterialMerchanExterno { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PossuiMaterialMerchanExterno { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PossuiMaterialMerchanExternoConcorrencia { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string TempoReposicaoConserto { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PdvPossuiAdesivo { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string FreqVisitaVendedor { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PdvSabeInformarPromo { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PdvSabeInformarNumPromo { get; set; }

    [StringLength(4)]
    [Unicode(false)]
    public string NrCadastroPromocao { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string IndiceSatisfacao { get; set; }

    public int? idAcesso { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string CpfCnpjPDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string NomePDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string EnderecoPDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string BairroPDV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string CidadePDV { get; set; }

    [Unicode(false)]
    public string Observacao { get; set; }

    [Unicode(false)]
    public string NomeFantasia { get; set; }

    [Unicode(false)]
    public string QtdChipSKU { get; set; }

    [Unicode(false)]
    public string QtdChipHROutOperadoras { get; set; }

    [Unicode(false)]
    public string QtdChipSKUOutOperadoras { get; set; }

    [Unicode(false)]
    public string FaturamentoRecarga { get; set; }

    [Unicode(false)]
    public string QtdChipHR { get; set; }
}