// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("QUALIDADE_BD_MANUAL_AUDIT")]
public partial class QUALIDADE_BD_MANUAL_AUDIT
{
    [Key]
    public int ID { get; set; }

    public int ID_LAST_STATUS { get; set; }

    public int LOGIN_ANALISTA { get; set; }

    public int LOGIN_RESPONSAVEL { get; set; }

    public int ANOMES { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string LOJA { get; set; }

    public int CENT { get; set; }

    public int CD { get; set; }

    public int ORDEM_VEND { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string TPOV { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string TIPO_MOVIMENTO { get; set; }

    public int CPF_CNPJ { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string MATERIAL { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATA_NF { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string N_DE_SERIE { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? VALOR_NF { get; set; }

    public int NUMERO_PED { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string CRIADO_POR { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string NM_PLANO { get; set; }

    public bool? FIDELIZAÇÃO { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string TIPO_JUST_FIDELIZACAO { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string LINHA_FIDELIZADA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_FIDELIZACAO { get; set; }

    public bool? MULTA_FAT_FID { get; set; }

    public bool? IMEI_NEXT { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string MOTIVO_EXCECAO_FIDELIZACAO { get; set; }

    public bool? RENOVA { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string N_VOUCHER { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_EMISSAO { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? VL_VOUCHER { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? VALOR_NA_TABELA_DE_PREÇO { get; set; }

    public bool? DIGITALIZADO { get; set; }

    public int? N_PROTOCOLO_GED { get; set; }

    public bool? CHAMADO { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string N_CHAMADO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_CHAMADO { get; set; }

    public bool? TICKET_RH { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_ABERTURA_TICKET { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string N_TICKET { get; set; }

    [Unicode(false)]
    public string ACAO_CORRETIVA { get; set; }

    [Unicode(false)]
    public string ACAO_PREVENTIVA { get; set; }

    [Unicode(false)]
    public string JUSTIFICATIVA_LOJA { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string AVALIACAO_REGIONAL { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string RETORNO_REGIONAL { get; set; }

    [InverseProperty("ID_FATURAMENTONavigation")]
    public virtual ICollection<FAT_MANUAL_STATUS> FAT_MANUAL_STATUSes { get; set; } = new List<FAT_MANUAL_STATUS>();
}