// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("RELACAO_EMAILS_VIVO_MAIS")]
public partial class RELACAO_EMAILS_VIVO_MAI
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(7)]
    [Unicode(false)]
    public string REGIONAL { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string EMAIL { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string SENHA { get; set; }
}