// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("RESET_SENHA_SISTEMAS")]
public partial class RESET_SENHA_SISTEMA
{
    [Key]
    public int ID { get; set; }

    public int IdReset { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Sistema { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Data { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Senha { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string MotivoRejeite { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataRejeite { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataSenha { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataRejeiteGc { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string MotivoRejeiteGc { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataAceiteGc { get; set; }

    [ForeignKey("IdReset")]
    [InverseProperty("RESET_SENHA_SISTEMAs")]
    public virtual RESET_SENHA IdResetNavigation { get; set; }
}