// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("RESET_SENHA")]
public partial class RESET_SENHA
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Login { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Matricula { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataSolicitacao { get; set; }

    public int idAcesso { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Ddd { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Uf { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string regional { get; set; }

    [InverseProperty("IdResetNavigation")]
    public virtual ICollection<RESET_SENHA_SISTEMA> RESET_SENHA_SISTEMAs { get; set; } = new List<RESET_SENHA_SISTEMA>();

    [ForeignKey("idAcesso")]
    [InverseProperty("RESET_SENHAs")]
    public virtual ACESSO idAcessoNavigation { get; set; }
}