// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("SAGRE_REAL_COBERTURA_GPON")]
public partial class SAGRE_REAL_COBERTURA_GPON
{
    [StringLength(50)]
    [Unicode(false)]
    public string UF { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CIDADE { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ARMARIO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CLLI_CODE_TBS { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TIPO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TITULO { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string LOGRADOURO { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CEP_DIR { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CEP_ESQ { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CAIXA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LOTE_COBERTURA { get; set; }

    [Column("LINHAS INSTALADAS")]
    [StringLength(50)]
    [Unicode(false)]
    public string LINHAS_INSTALADAS { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string USADOS_CAIXA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QUANTIDADE_LIVRE_CAIXA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string STATUS_LOTE { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QUANTIDADE_MERCADO_RA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QUANTIDADE_MERCADO_RB { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QUANTIDADE_MERCADO_RC { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QUANTIDADE_MERCADO_NA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QUANTIDADE_MERCADO_NB { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QUANTIDADE_MERCADO_NC { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ANTENA_COLETIVA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CAPACIDADE_CAIXA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DISPONIVEIS_CAIXA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TIPO_GPON { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LIVRE_CONDICIONADO_CAIXA { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string QUTY_SPL_PRI_LIVRES { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MIN_PORTAS_SP_LIVRES { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TOPOLOGIA_SP_1N { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string COD_LOG { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CNL { get; set; }
}