// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("SAVING_CADASTRO")]
public partial class SAVING_CADASTRO
{
    [Key]
    public int id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string mesAcao { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string ddd { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string rede { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string tipoAcao { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string opcaoAcao { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string oferta { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string periodoInicial { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string periodoFinal { get; set; }

    [Column(TypeName = "text")]
    public string descricao { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? valorAcao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataSolicitacao { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string status { get; set; }

    public int IdAcesso { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? valorPlanejado { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string valorEstimadoRetorno { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ParecerMKT { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ParecerCanal { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DataParecerMKT { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DataParecerCanal { get; set; }

    [Unicode(false)]
    public string ObsMKT { get; set; }

    [Unicode(false)]
    public string ObsCanal { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Necessita_Parecer_MKT { get; set; }

    [InverseProperty("ID_SAVINGNavigation")]
    public virtual ICollection<SAVING_EVIDENCIA> SAVING_EVIDENCIAs { get; set; } = new List<SAVING_EVIDENCIA>();
}