// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("SAVING_CADASTRO_BKP")]
public partial class SAVING_CADASTRO_BKP
{
    [Key]
    public int id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string mesAcao { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string ddd { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string rede { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string tipoAcao { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string opcaoAcao { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string oferta { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string periodoInicial { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string periodoFinal { get; set; }

    [Column(TypeName = "text")]
    public string descricao { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? valorAcao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataSolicitacao { get; set; }

    public int IdAcesso { get; set; }

    [ForeignKey("IdAcesso")]
    [InverseProperty("SAVING_CADASTRO_BKPs")]
    public virtual ACESSO IdAcessoNavigation { get; set; }

    [InverseProperty("ID_SAVINGNavigation")]
    public virtual ICollection<SAVING_EVIDENCIAS_BKP> SAVING_EVIDENCIAS_BKPs { get; set; } = new List<SAVING_EVIDENCIAS_BKP>();
}