// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("SOLICITACAO_APARELHO_CHIP")]
public partial class SOLICITACAO_APARELHO_CHIP
{
    public int ID { get; set; }

    public int? IdSolicitacao { get; set; }

    [Unicode(false)]
    public string Solicitacao { get; set; }

    [Unicode(false)]
    public string IMEI { get; set; }

    [Unicode(false)]
    public string ICCID { get; set; }

    [StringLength(350)]
    [Unicode(false)]
    public string Tipo_Venda { get; set; }

    public int? IdPedido { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string NrSerial { get; set; }
}