// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("SOLICITACAO")]
public partial class SOLICITACAO
{
    public int ID { get; set; }

    [Unicode(false)]
    public string Matricula { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DATASOLICITACAO { get; set; }

    [Unicode(false)]
    public string Status { get; set; }

    public int? IdBoleta { get; set; }

    [StringLength(350)]
    [Unicode(false)]
    public string Tipo_Venda { get; set; }
}