// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("T_VIC_VNDA_MANUAL_AUDIT")]
public partial class T_VIC_VNDA_MANUAL_AUDIT
{
    [StringLength(128)]
    [Unicode(false)]
    public string LOJA { get; set; }

    [StringLength(26)]
    [Unicode(false)]
    public string CENT { get; set; }

    [Column(TypeName = "NUMBER(38)")]
    public decimal? CD { get; set; }

    [Column(TypeName = "NUMBER(38)")]
    public decimal? ORDEM_VEND { get; set; }

    [StringLength(26)]
    [Unicode(false)]
    public string TPOV { get; set; }

    [StringLength(26)]
    [Unicode(false)]
    public string CPF_CNPJ { get; set; }

    [StringLength(26)]
    [Unicode(false)]
    public string MATERIAL { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string DATA_NF { get; set; }

    [Column(TypeName = "NUMBER(38)")]
    public decimal? N_DE_SERIE { get; set; }

    [Column(TypeName = "NUMBER(38)")]
    public decimal? VALOR_NF { get; set; }

    [Column(TypeName = "NUMBER(38)")]
    public decimal? NUMERO_PED { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string CRIADO_POR { get; set; }

    [StringLength(128)]
    [Unicode(false)]
    public string NM_PLANO { get; set; }

    [StringLength(26)]
    [Unicode(false)]
    public string APRL_DPAV { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string STATUS_DA_FIDELIZAÇÃO { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string NÚMERO_DA_LINHA_FIDELIZADA { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string VIVO_RENOVA_NÚMERO_DO_VOUCHER_DO_VIVO_RENOVA { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string DATA_DA_EMISSÃO_DO_VOUCHER_DO_VIVO_RENOVA { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string VALOR_DO_VOUCHER_VIVO_RENOVA { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string VIVO_VALORIZA_VALOR_DO_RESGATE_DA_PONTUAÇÃO_DO_VIVO_VALORIZA { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string VALOR_DO_RESGATE_VIVO_VALORIZA { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string DATA_DO_REGATE_DO_VIVO_VALORIZA { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string VALOR_NA_TABELA_DE_PREÇO { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string DELTA_DO_SUBSÍDIO_X_FATURAMENTO { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string PROTOCOLO_DE_DIGITALIZAÇÃO { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string LOGIN_RESPONSÁVEL { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string NÚMERO_DO_CHAMADO { get; set; }

    [StringLength(128)]
    [Unicode(false)]
    public string AVALIÇÃO_REGIONAL { get; set; }

    [StringLength(128)]
    [Unicode(false)]
    public string EMAIL_DO_RESPONSÁVEL_DA_REGIONAL { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string ANOMES { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string RETORNO_REGIONAL { get; set; }

    [Key]
    [StringLength(20)]
    [Unicode(false)]
    public string ID { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ISSAVED { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ISRESPONDIDO { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string HORA_RETORNO_FAT { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string NOME_RETORNO_FAT { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string MOTIVO_RETORNO_FAT { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string AUDITORIA { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string STATUS_DEV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string DT_DEV { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string RESP_DEV { get; set; }

    [Unicode(false)]
    public string OBSERVACAO_LOJA { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string APARELHO { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string TIPO_MOVIMENTO { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string TICKET_RH { get; set; }
}