// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("TABELA DE PRECOS")]
public partial class TABELA_DE_PRECO
{
    [Column("NOME DPGC")]
    [StringLength(255)]
    public string NOME_DPGC { get; set; }

    [Column("NOME COMERCIAL")]
    [StringLength(255)]
    public string NOME_COMERCIAL { get; set; }

    [StringLength(255)]
    public string ALTERACOES { get; set; }

    public double? PONTUACAO { get; set; }

    [StringLength(550)]
    [Unicode(false)]
    public string PLANO { get; set; }

    [Column("PLANO FOCO")]
    [StringLength(550)]
    [Unicode(false)]
    public string PLANO_FOCO { get; set; }

    [Column("PRECO ANTIGO")]
    public double? PRECO_ANTIGO { get; set; }

    public double? PRECO { get; set; }

    [Column("PRECO RENOVA")]
    [StringLength(255)]
    public string PRECO_RENOVA { get; set; }

    [Column("DATA INICIO")]
    [StringLength(255)]
    public string DATA_INICIO { get; set; }

    [StringLength(255)]
    public string PRODUTO { get; set; }

    [StringLength(255)]
    public string REGIAO { get; set; }

    [StringLength(255)]
    public string FABRICANTE { get; set; }

    [Column("NOME SISTEMICO")]
    [StringLength(255)]
    public string NOME_SISTEMICO { get; set; }
}