// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("TABELA_VALORES_COMISSIONAMENTO")]
public partial class TABELA_VALORES_COMISSIONAMENTO
{
    [StringLength(255)]
    public string desc_tipo_comissao { get; set; }

    public double? Mes1 { get; set; }

    public double? Mes2 { get; set; }

    public double? Mes3 { get; set; }

    public double? Mes4 { get; set; }

    [Column("Tipo 2")]
    [StringLength(255)]
    public string Tipo_2 { get; set; }

    [StringLength(255)]
    public string cod_credenc { get; set; }

    [StringLength(255)]
    public string REDE { get; set; }
}