// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("TABELAO_SERVICO_FIXA")]
public partial class TABELAO_SERVICO_FIXA
{
    [Key]
    public int Id { get; set; }

    [StringLength(45)]
    public string Servico { get; set; }

    [StringLength(10)]
    public string CategoriaServico { get; set; }
}