// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("TRAJETOS_PRESTACAO_KM")]
public partial class TRAJETOS_PRESTACAO_KM
{
    public int ID { get; set; }

    public int? IDPRESTACAO { get; set; }

    public int? KMANTERIOR { get; set; }

    public int? KMATUAL { get; set; }

    public int? KMSRODADOS { get; set; }

    [Unicode(false)]
    public string INTINERARIO { get; set; }

    public int? DIA { get; set; }
}