// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class V_QUALI_FPD_FIXA
{
    [StringLength(12)]
    public string ANO_MES { get; set; }

    [StringLength(255)]
    public string DDD { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string DIVISAO { get; set; }

    [StringLength(255)]
    public string CANAL { get; set; }

    [StringLength(255)]
    public string LOGIN_VNDA { get; set; }

    [StringLength(255)]
    public string CD_CRDN { get; set; }

    [StringLength(255)]
    public string REDE { get; set; }

    [StringLength(255)]
    public string NM_FNTS { get; set; }

    [StringLength(255)]
    public string TIPO_CLIENTE { get; set; }

    [StringLength(255)]
    public string TECNOLOGIA { get; set; }

    [StringLength(255)]
    public string F_OVER_8 { get; set; }

    [StringLength(255)]
    public string F_OVER_15 { get; set; }

    [StringLength(255)]
    public string F_OVER_30 { get; set; }

    [StringLength(255)]
    public string F_OVER_60 { get; set; }

    [StringLength(255)]
    public string F_OVER_180 { get; set; }
}