// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
[Table("VALIDACAO_HC")]
public partial class VALIDACAO_HC
{
    [StringLength(255)]
    public string MATRICULA { get; set; }

    [StringLength(255)]
    public string NOME { get; set; }

    [StringLength(255)]
    public string REGIONAL { get; set; }

    public double? UNIDADE { get; set; }

    [StringLength(255)]
    public string AREA { get; set; }

    public double? COD_CARGO { get; set; }

    [StringLength(255)]
    public string CARGO { get; set; }

    [StringLength(255)]
    public string DATA_ADMISSAO { get; set; }

    [StringLength(255)]
    public string STATUS { get; set; }

    [StringLength(255)]
    public string TIPO_DE_AUSENCIA_OU_PRESENÇA { get; set; }

    [StringLength(255)]
    public string INICIO { get; set; }

    [StringLength(255)]
    public string FIM { get; set; }

    [StringLength(255)]
    public string DIVERGENCIA { get; set; }

    [StringLength(255)]
    public string OBS { get; set; }

    public double? ANOMES { get; set; }
}