// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("VALOR_SAVING")]
public partial class VALOR_SAVING
{
    [Unicode(false)]
    public string REDE { get; set; }

    [Column(TypeName = "numeric(14, 2)")]
    public decimal? TOTAL { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string UF { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string DDD { get; set; }

    [Key]
    public int ID { get; set; }
}