// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Keyless]
public partial class VIEW_ULTIMA_MOVIMENTACAO_DESCREDENCIAMENTO
{
    [StringLength(50)]
    [Unicode(false)]
    public string ADABAS { get; set; }

    public int? ID { get; set; }
}