// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("VIVO_VISITA_GERENTE_GERAL")]
public partial class VIVO_VISITA_GERENTE_GERAL
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string Ddd { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string Loja { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string TipoAbertura { get; set; }

    [Required]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Data { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataCadastro { get; set; }

    public int IdAcesso { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Nota { get; set; }

    [InverseProperty("IdAberturaNavigation")]
    public virtual ICollection<VIVO_VISITA_GERENTE_GERAL_ESTRUTURA_OPERACAO> VIVO_VISITA_GERENTE_GERAL_ESTRUTURA_OPERACAOs { get; set; } = new List<VIVO_VISITA_GERENTE_GERAL_ESTRUTURA_OPERACAO>();

    [InverseProperty("IdAberturaNavigation")]
    public virtual ICollection<VIVO_VISITA_GERENTE_GERAL_PESSOA> VIVO_VISITA_GERENTE_GERAL_PESSOAs { get; set; } = new List<VIVO_VISITA_GERENTE_GERAL_PESSOA>();

    [InverseProperty("IdAberturaNavigation")]
    public virtual ICollection<VIVO_VISITA_GERENTE_GERAL_PROCESSO> VIVO_VISITA_GERENTE_GERAL_PROCESSOs { get; set; } = new List<VIVO_VISITA_GERENTE_GERAL_PROCESSO>();

    [InverseProperty("IdAberturaNavigation")]
    public virtual ICollection<VIVO_VISITA_GERENTE_GERAL_RESULTADO> VIVO_VISITA_GERENTE_GERAL_RESULTADOs { get; set; } = new List<VIVO_VISITA_GERENTE_GERAL_RESULTADO>();
}