// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("VIVO_VISITA_CANAL_TERRITORIO_PESSOAS")]
public partial class VIVO_VISITA_CANAL_TERRITORIO_PESSOA
{
    [Key]
    public int Id { get; set; }

    public int IdAbertura { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasExisteVagaOpenSimNao { get; set; }

    [Unicode(false)]
    public string PessoasExisteVagaOpenObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasPossuiVagaExcedenteReintegracaoSimNao { get; set; }

    [Unicode(false)]
    public string PessoasPossuiVagaExcedenteReintegracaoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarExisteFuncionarioAfastadoSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarExisteFuncionarioAfastadoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarexisteFuncionarioEstabilidadeSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarexisteFuncionarioEstabilidadeObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarUniformeSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarUniformeObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarAbsenteismoSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarAbsenteismoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarFechamentoPontoHCSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarFechamentoPontoHCObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarDocumentacaoFiscalizacaoSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarDocumentacaoFiscalizacaoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasTodosEstaoCrachaSimNao { get; set; }

    [Unicode(false)]
    public string PessoasTodosEstaoCrachaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarApresentacaoPessoalEquipeSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarApresentacaoPessoalEquipeObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarAdesaoEscalaSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarAdesaoEscalaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarClimaEquipeSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarClimaEquipeObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasRealizarInteracaoEquipeSimNao { get; set; }

    [Unicode(false)]
    public string PessoasRealizarInteracaoEquipeObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasTodosEstaoSenhasLiberadasAcessoSistemasSimNao { get; set; }

    [Unicode(false)]
    public string PessoasTodosEstaoSenhasLiberadasAcessoSistemasObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarAdesaoTreinamentosSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarAdesaoTreinamentosObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVerificarEscalaFeriasSimNao { get; set; }

    [Unicode(false)]
    public string PessoasVerificarEscalaFeriasObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasParticiparMatinaisVespertinasSimNao { get; set; }

    [Unicode(false)]
    public string PessoasParticiparMatinaisVespertinasObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasConfirmarTodosCargosEstaoRealizandoAtuacaoSimNao { get; set; }

    [Unicode(false)]
    public string PessoasConfirmarTodosCargosEstaoRealizandoAtuacaoObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    [ForeignKey("IdAbertura")]
    [InverseProperty("VIVO_VISITA_CANAL_TERRITORIO_PESSOAs")]
    public virtual VIVO_VISITA_CANAL_TERRITORIO_ABERTURA IdAberturaNavigation { get; set; }
}