// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("VIVO_VISITA_GERENTE_GERAL_ESTRUTURA_OPERACAO")]
public partial class VIVO_VISITA_GERENTE_GERAL_ESTRUTURA_OPERACAO
{
    [Key]
    public int Id { get; set; }

    public int IdAbertura { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesMateriasTradeTVConformeMapaPDVSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesMateriasTradeTVConformeMapaPDVPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesMateriasTradeTVConformeMapaPDVObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesMaterialTradeVencidoDescartadoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesMaterialTradeVencidoDescartadoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesMaterialTradeVencidoDescartadoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesCRAcessoMapaPDVSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesCRAcessoMapaPDVPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesCRAcessoMapaPDVObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesCartazesRegulatoriosCodigoDefesaConsumidorExpostoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesCartazesRegulatoriosCodigoDefesaConsumidorExpostoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesCartazesRegulatoriosCodigoDefesaConsumidorExpostoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesPromotoresFabricantesUniformizadosSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesPromotoresFabricantesUniformizadosPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesPromotoresFabricantesUniformizadosObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesTabelaPrecoComDivulgacaoAparelhosSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesTabelaPrecoComDivulgacaoAparelhosPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesTabelaPrecoComDivulgacaoAparelhosObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesPrecificadoresAcordoTabelaPrecoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesPrecificadoresAcordoTabelaPrecoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesPrecificadoresAcordoTabelaPrecoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesAparelhosDegustacaoLigadosSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesAparelhosDegustacaoLigadosPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesAparelhosDegustacaoLigadosObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesAparelhosExpostosTradeSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesAparelhosExpostosTradePeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesAparelhosExpostosTradeObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesUrnaReciclarPegaBemPositivadaSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesUrnaReciclarPegaBemPositivadaPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesUrnaReciclarPegaBemPositivadaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesRevistaMundoVivoAtualizadaSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesRevistaMundoVivoAtualizadaPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesRevistaMundoVivoAtualizadaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesArvoreOfertasUtilizadaEquipeSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesArvoreOfertasUtilizadaEquipePeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesArvoreOfertasUtilizadaEquipeObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesEquipeAlinhadaCartazPositivadoAtitudesPegamBemSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesEquipeAlinhadaCartazPositivadoAtitudesPegamBemPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesEquipeAlinhadaCartazPositivadoAtitudesPegamBemObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesColaboradoresApresentacaoManualSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesColaboradoresApresentacaoManualPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesColaboradoresApresentacaoManualObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesEquipeAptaChamarSenhasSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesEquipeAptaChamarSenhasPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesEquipeAptaChamarSenhasObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesGNSuporteEquipeVendasSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesGNSuporteEquipeVendasPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesGNSuporteEquipeVendasObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesCRAbordandoClientesEsperaSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesCRAbordandoClientesEsperaPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesCRAbordandoClientesEsperaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesGuruIncentivandoMeuVivoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesGuruIncentivandoMeuVivoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesGuruIncentivandoMeuVivoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesCNsSeguindoScriptdeVendasSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesCNsSeguindoScriptdeVendasPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesCNsSeguindoScriptdeVendasObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesEquipeSenhaLiberadaAcessoSistemasAtendimentoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesEquipeSenhaLiberadaAcessoSistemasAtendimentoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesEquipeSenhaLiberadaAcessoSistemasAtendimentoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesMarcacaoTotemEmissãoSenhaEnvioSMSClienteSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesMarcacaoTotemEmissãoSenhaEnvioSMSClientePeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesMarcacaoTotemEmissãoSenhaEnvioSMSClienteObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesGestaoChamadosManutencaoTISimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesGestaoChamadosManutencaoTIPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesGestaoChamadosManutencaoTIObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesPainelSenhaFuncionandoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesPainelSenhaFuncionandoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesPainelSenhaFuncionandoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesVivoBoxFuncionandoDegustaçãoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesVivoBoxFuncionandoDegustaçãoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesVivoBoxFuncionandoDegustaçãoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesTabletFuncionandoUtilizadoVendaSustentavelSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesTabletFuncionandoUtilizadoVendaSustentavelPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesTabletFuncionandoUtilizadoVendaSustentavelObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesComputadoresImpressorasFuncionandoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesComputadoresImpressorasFuncionandoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesComputadoresImpressorasFuncionandoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesAlarmesAparelhosFuncionandoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesAlarmesAparelhosFuncionandoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesAlarmesAparelhosFuncionandoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesSistemaSegurançaLojaOperandoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesSistemaSegurançaLojaOperandoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesSistemaSegurançaLojaOperandoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesMobiliariosBomEstadoDentroPadraoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesMobiliariosBomEstadoDentroPadraoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesMobiliariosBomEstadoDentroPadraoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesLampadasAcesasTonalidadesSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesLampadasAcesasTonalidadesPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesLampadasAcesasTonalidadesObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesVitrineFachadaLuzesAcesasMesmasTonalidadesSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesVitrineFachadaLuzesAcesasMesmasTonalidadesPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesVitrineFachadaLuzesAcesasMesmasTonalidadesObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesArCondiconadoFuncionandoTemperaturaAdequadaSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesArCondiconadoFuncionandoTemperaturaAdequadaPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesArCondiconadoFuncionandoTemperaturaAdequadaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesParedesInternasExternasMateriaisColadosSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesParedesInternasExternasMateriaisColadosPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesParedesInternasExternasMateriaisColadosObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesLojaLimpaeOganizadaSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesLojaLimpaeOganizadaPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesLojaLimpaeOganizadaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesNaoPossuiAcumuloMateriaisDesusoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesNaoPossuiAcumuloMateriaisDesusoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesNaoPossuiAcumuloMateriaisDesusoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesLixeirasLimpasLocalApropriadoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesLixeirasLimpasLocalApropriadoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesLixeirasLimpasLocalApropriadoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesFiacaoNaoExpostaOrganizadaSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesFiacaoNaoExpostaOrganizadaPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesFiacaoNaoExpostaOrganizadaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesFechamentoFinanceiroDiaAnteriorPendenciasSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesFechamentoFinanceiroDiaAnteriorPendenciasPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesFechamentoFinanceiroDiaAnteriorPendenciasObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesPossuiSinalVivoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesPossuiSinalVivoPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesPossuiSinalVivoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaOperacoesImpressorasSemDocumentosSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EstruturaOperacoesImpressorasSemDocumentosPeriodicidade { get; set; }

    [Unicode(false)]
    public string EstruturaOperacoesImpressorasSemDocumentosObs { get; set; }

    [ForeignKey("IdAbertura")]
    [InverseProperty("VIVO_VISITA_GERENTE_GERAL_ESTRUTURA_OPERACAOs")]
    public virtual VIVO_VISITA_GERENTE_GERAL IdAberturaNavigation { get; set; }
}