// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("VIVO_VISITA_GERENTE_GERAL_PROCESSOS")]
public partial class VIVO_VISITA_GERENTE_GERAL_PROCESSO
{
    [Key]
    public int Id { get; set; }

    public int IdAbertura { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosManualLojaPropriaAtualizadoDisponívelSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosManualLojaPropriaAtualizadoDisponívelPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosManualLojaPropriaAtualizadoDisponívelObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosQuadroAvisosAtualizadoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosQuadroAvisosAtualizadoPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosQuadroAvisosAtualizadoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosAtaReuniaoRealizadaSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosAtaReuniaoRealizadaPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosAtaReuniaoRealizadaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosGestaoMaterialEscritorioSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosGestaoMaterialEscritorioPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosGestaoMaterialEscritorioObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosUpLoadBookFotograficoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosUpLoadBookFotograficoPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosUpLoadBookFotograficoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosAlvaraFuncionamentoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosAlvaraFuncionamentoPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosAlvaraFuncionamentoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosAuditoriaBVCSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosAuditoriaBVCPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosAuditoriaBVCObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosAnaliseIndicadoresQualidadeSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosAnaliseIndicadoresQualidadePeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosAnaliseIndicadoresQualidadeObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosAnaliseIndicadoresTempoPlanoAcaoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosAnaliseIndicadoresTempoPlanoAcaoPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosAnaliseIndicadoresTempoPlanoAcaoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosEquipeAlinhadaGestaoDocumentalSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosEquipeAlinhadaGestaoDocumentalPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosEquipeAlinhadaGestaoDocumentalObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosGestaoIrregularidadesApontadasVivoGEDSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosGestaoIrregularidadesApontadasVivoGEDPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosGestaoIrregularidadesApontadasVivoGEDObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosEquipeAlinhadaAtendimentoPJSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosEquipeAlinhadaAtendimentoPJPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosEquipeAlinhadaAtendimentoPJObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosMasterBoxFechadaSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosMasterBoxFechadaPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosMasterBoxFechadaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosConferenciaEstoqueConformeITSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosConferenciaEstoqueConformeITPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosConferenciaEstoqueConformeITObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosConferenciaRPARConformeITSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosConferenciaRPARConformeITPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosConferenciaRPARConformeITObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosConferenciaAleatoriaAparelhosAbertosDemonstracaoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosConferenciaAleatoriaAparelhosAbertosDemonstracaoPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosConferenciaAleatoriaAparelhosAbertosDemonstracaoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosBaixaProgramaPontosRealizadaSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosBaixaProgramaPontosRealizadaPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosBaixaProgramaPontosRealizadaObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosPendenciasEmissaoNotasFiscaisSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosPendenciasEmissaoNotasFiscaisPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosPendenciasEmissaoNotasFiscaisObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosCaixaConferirFundoTrocoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosCaixaConferirFundoTrocoPeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosCaixaConferirFundoTrocoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProcessosCofreFechadoSegredoChaveSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProcessosCofreFechadoSegredoChavePeriodicidade { get; set; }

    [Unicode(false)]
    public string ProcessosCofreFechadoSegredoChaveObs { get; set; }

    [ForeignKey("IdAbertura")]
    [InverseProperty("VIVO_VISITA_GERENTE_GERAL_PROCESSOs")]
    public virtual VIVO_VISITA_GERENTE_GERAL IdAberturaNavigation { get; set; }
}