// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("VIVO_VISITA_PASSAGEM_LOJA_ESTRUTURA_PROCESSOS")]
public partial class VIVO_VISITA_PASSAGEM_LOJA_ESTRUTURA_PROCESSO
{
    [Key]
    public int Id { get; set; }

    public int IdAbertura { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosMobiliariosReparoOSAbertaRegularizacaoSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosMobiliariosReparoOSAbertaRegularizacaoObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosMobiliariosReparoOSAbertaRegularizacaoPrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosMobiliariosReparoOSAbertaRegularizacaoResponsavel { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosEquipamentosReparoChamadosAbertosRegularizacaoSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosEquipamentosReparoChamadosAbertosRegularizacaoObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosEquipamentosReparoChamadosAbertosRegularizacaoPrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosEquipamentosReparoChamadosAbertosRegularizacaoResponsavel { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosChamadosAbertosDentroPrazoCobrançaSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosChamadosAbertosDentroPrazoCobrançaObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosChamadosAbertosDentroPrazoCobrançaPrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosChamadosAbertosDentroPrazoCobrançaResponsavel { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosLojaPossuiControleNovoGerenteSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosLojaPossuiControleNovoGerenteObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosLojaPossuiControleNovoGerentePrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosLojaPossuiControleNovoGerenteResponsavel { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosLojaOrganizadaSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosLojaOrganizadaObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosLojaOrganizadaPrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosLojaOrganizadaResponsavel { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosEquipamentosMobiliariosNUsadosAguardandoColetaSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosEquipamentosMobiliariosNUsadosAguardandoColetaObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosEquipamentosMobiliariosNUsadosAguardandoColetaPrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosEquipamentosMobiliariosNUsadosAguardandoColetaResponsavel { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosAlarmesReinicializadosSenhaNovosGerentesSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosAlarmesReinicializadosSenhaNovosGerentesObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosAlarmesReinicializadosSenhaNovosGerentesPrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosAlarmesReinicializadosSenhaNovosGerentesResponsavel { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosLojaPastaAtendeProcedimentoContingenciaGSSSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosLojaPastaAtendeProcedimentoContingenciaGSSObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosLojaPastaAtendeProcedimentoContingenciaGSSPrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosLojaPastaAtendeProcedimentoContingenciaGSSResponsavel { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosLojaQuadroAvisosSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosLojaQuadroAvisosObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosLojaQuadroAvisosPrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosLojaQuadroAvisosResponsavel { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosEstaoGuardadosDocumentosFiscaisSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosEstaoGuardadosDocumentosFiscaisObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosEstaoGuardadosDocumentosFiscaisPrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosEstaoGuardadosDocumentosFiscaisResponsavel { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosDemaisConsideracoes { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EstruturaProcessosLojaPossuiMaterialEscritorioGuardadoAdequadoSimNao { get; set; }

    [Unicode(false)]
    public string EstruturaProcessosLojaPossuiMaterialEscritorioGuardadoAdequadoObs { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstruturaProcessosLojaPossuiMaterialEscritorioGuardadoAdequadoPrazo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EstruturaProcessosLojaPossuiMaterialEscritorioGuardadoAdequadoResponsavel { get; set; }
}