// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("VIVO_VISITA_PASSAGEM_ABERTURA")]
public partial class VIVO_VISITA_PASSAGEM_ABERTURA
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string Ddd { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string Loja { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string TipoAbertura { get; set; }

    [Required]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Data { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataCadastro { get; set; }

    public int IdAcesso { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Extensao { get; set; }

    public byte[] Arquivo { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Nota { get; set; }

    [ForeignKey("IdAcesso")]
    [InverseProperty("VIVO_VISITA_PASSAGEM_ABERTURAs")]
    public virtual ACESSO IdAcessoNavigation { get; set; }
}