// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared_Static_Class.Data;

[Table("VIVO_VISITA_GERENTE_GERAL_PESSOAS")]
public partial class VIVO_VISITA_GERENTE_GERAL_PESSOA
{
    [Key]
    public int Id { get; set; }

    public int IdAbertura { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasPlanejamentoDivulgacaoFériasSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PessoasPlanejamentoDivulgacaoFériasPeriodicidade { get; set; }

    [Unicode(false)]
    public string PessoasPlanejamentoDivulgacaoFériasObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasTodosColaboradoresPossuemLinhaFuncionalSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PessoasTodosColaboradoresPossuemLinhaFuncionalPeriodicidade { get; set; }

    [Unicode(false)]
    public string PessoasTodosColaboradoresPossuemLinhaFuncionalObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasTreinamentoFocoRealizadoEquipeSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PessoasTreinamentoFocoRealizadoEquipePeriodicidade { get; set; }

    [Unicode(false)]
    public string PessoasTreinamentoFocoRealizadoEquipeObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasEquipeAcessoPlataformasTreinamentoSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PessoasEquipeAcessoPlataformasTreinamentoPeriodicidade { get; set; }

    [Unicode(false)]
    public string PessoasEquipeAcessoPlataformasTreinamentoObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasFeedbackindividualderesultadosSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PessoasFeedbackindividualderesultadosPeriodicidade { get; set; }

    [Unicode(false)]
    public string PessoasFeedbackindividualderesultadosObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasGestaoPontoRealizadaSemanalmenteSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PessoasGestaoPontoRealizadaSemanalmentePeriodicidade { get; set; }

    [Unicode(false)]
    public string PessoasGestaoPontoRealizadaSemanalmenteObs { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PessoasVagasAbertoPossuemSPPSimNao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PessoasVagasAbertoPossuemSPPPeriodicidade { get; set; }

    [Unicode(false)]
    public string PessoasVagasAbertoPossuemSPPObs { get; set; }

    [ForeignKey("IdAbertura")]
    [InverseProperty("VIVO_VISITA_GERENTE_GERAL_PESSOAs")]
    public virtual VIVO_VISITA_GERENTE_GERAL IdAberturaNavigation { get; set; }
}